# Метод функциональных точек (Function Points Analysis, *FPA*)

**Четкая модель *FPA*. Расчет для новой функциональности.**

In [ ]:
def complexity(DET, RET):
  # если DET < 20 и RET = 1, то COMPL = Low; если 20 <= DET <= 50 и RET = 1, то COMPL = Low; если DET > 50 и RET=1, то COMPL = Average;
  # если DET < 20 и 2 <= RET <= 5, то COMPL = Low; если 20 <= DET <= 50 и 2 <= RET <= 5, то COMPL = Average; если DET > 50 и 2 <= RET <= 5, то COMPL = High;
  # если DET < 20 и RET > 5, то COMPL = Average; если 20 <= DET <= 50 и RET > 5, то COMPL = High; если DET > 5 0 и RET > 5, то COMPL = High;
    if DET < 20 and RET == 1:
        COMPL = "Low"
    elif 20 <= DET <= 50 and RET == 1:
        COMPL = "Low"
    elif DET > 50 and RET == 1:
        COMPL = "Average"
    elif DET < 20 and 2 <= RET <= 5:
        COMPL = "Low"
    elif 20 <= DET <= 50 and 2 <= RET <= 5:
        COMPL = "Average"
    elif DET > 50 and 2 <= RET <= 5:
        COMPL = "High"
    elif DET < 20 and RET > 5:
        COMPL = "Average"
    elif 20 <= DET <= 50 and RET > 5:
        COMPL = "High"
    elif DET > 50 and RET > 5:
        COMPL = "High"
    else:
        COMPL = "Undefined"  # Если ни одно из условий не выполнено

    return COMPL

In [ ]:
# Вводим начальные параметры для определения сложности данных:
DET = 18 # (Data Element Type) количество неповторяемых уникальных полей данных
RET = 2  # (Record Element Type) количество логических групп данных
print(f"При указанных выше значениях параметров DET и RET, сложность данных определяется как  {complexity(DET, RET)}")

При указанных выше значениях параметров DET и RET, сложность данных определяется как  Low


In [ ]:
# Оценка данных в невыровненных  функциональных точках (UFP) для внутренних логических файлов (ILFs) и внешних интерфейсных файлов (EIFs)
# Если complexity(DET, RET) = Low, то UFP_ILF = 7, если complexity(DET, RET) = Average, то UFP_ILF = 10, если complexity(DET, RET) = High, то UFP_ILF = 15;
# Если complexity(DET, RET) = Low, то UFP_EIF = 5, если complexity(DET, RET) = Average, то UFP_EIF = 7, если complexity(DET, RET) = High, то UFP_EIF = 10.
if complexity(DET, RET) == "Low":
    UFP_ILF = 7
    UFP_EIF = 5
elif complexity(DET, RET) == "Average":
    UFP_ILF = 10
    UFP_EIF = 7
elif complexity(DET, RET) == "High":
    UFP_ILF = 15
    UFP_EIF = 10
else:
    UFP_ILF = 0  # Значения по умолчанию, если сложность неопределена
    UFP_EIF = 0

In [ ]:
print(f"При указанных выше значениях параметров DET и RET, количество UFP(ILF) = {UFP_ILF}, UFP(EIF) = {UFP_EIF} невыровненных функциональных точек")

При указанных выше значениях параметров DET и RET, количество UFP(ILF) = 7, UFP(EIF) = 5 невыровненных функциональных точек


In [ ]:
# Функция расчета матрицы сложности внешних входных транзакций (EI)
def complexity1(DET1, FTR):
  # если DET1 < 5 и FTR < 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR < 2, то COMPL1 = Low; если DET1 > 15 и FTR < 2, то COMPL1 = Average;
  # если DET1 < 5 и FTR = 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR = 2, то COMPL1 = Average; если DET1 > 15 и FTR = 2, то COMPL1 = High;
  # если DET1 < 5 и FTR > 2, то COMPL1 = Average; если 5 <= DET1 <= 15 и FTR > 2, то COMPL1 = High; если DET1 > 15 и FTR > 2, то COMPL1 = High;
    if DET1 < 5 and FTR < 2:
        COMPL1 = "Low"
    elif 5 <= DET1 <= 15 and FTR < 2:
        COMPL1 = "Low"
    elif DET1 > 15 and FTR < 2:
        COMPL1 = "Average"
    elif DET1 < 5 and FTR == 2:
        COMPL1 = "Low"
    elif 5 <= DET1 <= 15 and FTR == 2:
        COMPL1 = "Average"
    elif DET1 > 15 and FTR == 2:
        COMPL1 = "High"
    elif DET1 < 5 and FTR > 2:
        COMPL1 = "Average"
    elif 5 <= DET1 <= 15 and FTR > 2:
        COMPL1 = "High"
    elif DET1 > 15 and FTR > 2:
        COMPL1 = "High"
    else:
        COMPL1 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено

    return COMPL1

In [ ]:
# Функция расчета матрицы сложности внешних выходных транзакций и внешних запросов (EO&EQ)
def complexity2(DET1, FTR):
  # если DET1 < 6 и FTR < 2, то COMPL2 = Low; если 6 <= ET1 <= 19 и FTR < 2, то COMPL2 = Low; если DET1 > 19 и FTR < 2, то COMPL2 = Average;
  # если DET1 < 6 и 2 <= FTR <= 3, то COMPL2 = Low; если 6 <= DET1 <= 19 и 2 <= FTR <= 3, то COMPL2 = Average; если DET1 > 19 и 2 <= FTR <= 3, то COMPL2 = High;
  # если DET1 < 6 и FTR > 3, то COMPL2 = Average; если 6 <= DET1 <= 19 и FTR > 3, то COMPL2 = High; если DET 1> 19 и FTR > 3, то COMPL2 = High;
 # Определение сложности на основе условий
    if DET1 < 6 and FTR < 2:
        COMPL2 = "Low"
    elif 6 <= DET1 <= 19 and FTR < 2:
        COMPL2 = "Low"
    elif DET1 > 19 and FTR < 2:
        COMPL2 = "Average"
    elif DET1 < 6 and 2 <= FTR <= 3:
        COMPL2 = "Low"
    elif 6 <= DET1 <= 19 and 2 <= FTR <= 3:
        COMPL2 = "Average"
    elif DET1 > 19 and 2 <= FTR <= 3:
        COMPL2 = "High"
    elif DET1 < 6 and FTR > 3:
        COMPL2 = "Average"
    elif 6 <= DET1 <= 19 and FTR > 3:
        COMPL2 = "High"
    elif DET1 > 19 and FTR > 3:
        COMPL2 = "High"
    else:
        COMPL2 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено
    return COMPL2

In [ ]:
# Вводим характеристики оценки сложности транзакций
DET1 = 18 # (Data Element Type) количество неповторяемых уникальных полей данных
FTR = 4   # (File Type Referenced) количество файлов (информационных объектов) типа ILF и/или EIF, модифицируемых или считываемых в транзакции
print(f"При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как {complexity1(DET1, FTR)},\n"
f"сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как {complexity2(DET1, FTR)}")

При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как High,
сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как High


In [ ]:
# Оценка сложности транзакций в невыровненных  функциональных точках (UFP)
# Если complexity1(DET1, FTR) = Low, то UFP_EI = 3, если complexity1(DET1, FTR) = Average, то UFP_EI = 4, если complexity1(DET1, FTR) = High, то UFP_EI = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EQ = 3, если complexity2(DET1, FTR) = Average, то UFP_EQ = 4, если complexity2(DET1, FTR) = High, то UFP_EQ = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EO = 4, если complexity2(DET1, FTR) = Average, то UFP_EO = 5, если complexity2(DET1, FTR) = High, то UFP_EO = 7;
if complexity1(DET1, FTR) == "Low":
    UFP_EI = 3
elif complexity1(DET1, FTR) == "Average":
    UFP_EI = 4
elif complexity1(DET1, FTR) == "High":
    UFP_EI = 6
else:
    UFP_EI = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EQ = 3
elif complexity2(DET1, FTR) == "Average":
    UFP_EQ = 4
elif complexity2(DET1, FTR) == "High":
    UFP_EQ = 6
else:
    UFP_EQ = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EO = 4
elif complexity2(DET1, FTR) == "Average":
    UFP_EO = 5
elif complexity2(DET1, FTR) == "High":
    UFP_EO = 7
else:
    UFP_EO = None  # Значение по умолчанию, если не определено

In [ ]:
print(f"При указанных выше значениях параметров DET1 и FTR, количество UFP(EI) = {UFP_EI}, UFP(EQ) = {UFP_EQ}, UFP(EO) = {UFP_EO} невыровненных функциональных точек")

При указанных выше значениях параметров DET1 и FTR, количество UFP(EI) = 6, UFP(EQ) = 6, UFP(EO) = 7 невыровненных функциональных точек


In [ ]:
# Расчет количества невыровненных функциональных точек
UFP = UFP_ILF + UFP_EIF + UFP_EI + UFP_EO + UFP_EQ
print(f"При рассчитанных выше значениях, суммарная оценка количества невыровненных функциональных точек UFP принимает значение {UFP}")

При рассчитанных выше значениях, суммарная оценка количества невыровненных функциональных точек UFP принимает значение 31


In [ ]:
# Определение значения фактора выравнивания (VAF)
DI1 = 4   # Обмен данными, показатель от 0 до 5 включительно
DI2 = 3   # Распределенная обработка данных, показатель от 0 до 5 включительно
DI3 = 5   # Производительность, показатель от 0 до 5 включительно
DI4 = 1   # Ограничения по аппаратным ресурсам, показатель от 0 до 5 включительно
DI5 = 0   # Транзакционная нагрузка, показатель от 0 до 5 включительно
DI6 = 5   # Интенсивность взаимодействия с пользователем, показатель от 0 до 5 включительно
DI7 = 5   # Эргономика (эффективность работы конечных пользователей), показатель от 0 до 5 включительно
DI8 = 0   # Интенсивность изменения данных (ILF) пользователями, показатель от 0 до 5 включительно
DI9 = 4   # Сложность обработки, показатель от 0 до 5 включительно
DI10 = 5  # Повторное использование, показатель от 0 до 5 включительно
DI11 = 3  # Удобство инсталляции, показатель от 0 до 5 включительно
DI12 = 5  # Удобство администрирования, показатель от 0 до 5 включительно
DI13 = 1  # Портируемость, показатель от 0 до 5 включительно
DI14 = 1    # Гибкость, показатель от 0 до 5 включительно
TDI = DI1 + DI2 + DI3 + DI4 + DI5 + DI6 + DI7 + DI8 + DI9 + DI10 + DI11 + DI12 + DI13 + DI14
print(f"При вышеуказанных системных параметрах DI1-DI14, суммарный эффект TDI принимает значение {TDI}")

При вышеуказанных системных параметрах DI1-DI14, суммарный эффект TDI принимает значение 42


In [ ]:
# Расчет значения фактора выравнивания VAF
VAF = (TDI * 0.01) + 0.65
print(f"При рассчитанном выше суммарном эффекте системных характеристик TDI, фактор выравнивания VAF принимает значение {VAF}")

При рассчитанном выше суммарном эффекте системных характеристик TDI, фактор выравнивания VAF принимает значение 1.07


In [ ]:
# Расчет количества выровненных функциональных точек (AFP)
AFP = UFP * VAF
print(f"При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение {AFP} выровненных функциональных точек")

При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение 33.17 выровненных функциональных точек


Метод анализа функциональных точек ничего не говорит о трудоемкости разработки оцененного продукта. Вопрос решается просто, если компания-разработчик имеет собственную статистику трудозатрат на реализацию функциональных точек. Если такой статистики нет, то для оценки трудоемкости и сроков проекта можно использовать метод *COCOMO II*. [Коротаев А.Н., Марчев Д.В. Экономика программной инженерии]

# Нечеткая модель *FPA*. Применение трапециевидных нечетких чисел 2 типа

Нечеткие трапециевидные числа второго типа имеют две ФП - верхнюю и нижнюю для ИНМ2Т и функции принадлежности и непринадлежности для интуиционистских НМ, отражающие сомнения эксперта в оценках границ нечеткости, т.е. правая и левая границы нечеткости имеют по 2 значения. Левая граница - это минимальное значение нечеткости, правая, соответственно, максимальное.

In [ ]:
# Функция сложения двух трапециевидных нечетких чисел (интуиционистских или интервальных 2 типа)
def add_intuitionistic_trapezoidal_fuzzy_numbers(fuzzy_number1, fuzzy_number2):
    # Сложение двух нечетких трапециевидных чисел
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number1
    (y1, y2, y3, y4), (y5, y6, y7, y8) = fuzzy_number2
    return ((x1 + y1, x2 + y2, x3 + y3, x4 + y4),
            (x5 + y5, x6 + y6, x7 + y7, x8 + y8))

In [ ]:
# Функция вычисления среднего арифметического дефаззифицированных значений двух функция принадлежности
def calculate_average(defuzzified_values):
    # Извлекаем значения из кортежа
    defuzzified_upper, defuzzified_lower = defuzzified_values
    # Вычисляем среднее арифметическое
    average = round((defuzzified_upper + defuzzified_lower) / 2, 3)
    return average

In [ ]:
# Определение сложности данных
def complexity(DET, RET):
    # Присвоим значения из трапециевидных чисел
    ((x1, x2, x3, x4), (x5, x6, x7, x8)) = DET
    ((y1, y2, y3, y4), (y5, y6, y7, y8)) = RET

    mean_DET = (x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8) / 8
    mean_RET = (y1 + y2 + y3 + y4 + y5 + y6 + y7 + y8) / 8

    # Используем условия для определения сложности
    if mean_DET < 20 and mean_RET == 1:
        COMPL = "Low"
    elif 20 <= mean_DET <= 50 and mean_RET == 1:
        COMPL = "Low"
    elif mean_DET > 50 and mean_RET == 1:
        COMPL = "Average"
    elif mean_DET < 20 and 1 < mean_RET <= 5:
        COMPL = "Low"
    elif 20 <= mean_DET <= 50 and 1 < mean_RET <= 5:
        COMPL = "Average"
    elif mean_DET > 50 and 1 < mean_RET <= 5:
        COMPL = "High"
    elif mean_DET < 20 and mean_RET > 5:
        COMPL = "Average"
    elif 20 <= mean_DET <= 50 and mean_RET > 5:
        COMPL = "High"
    elif mean_DET > 50 and mean_RET > 5:
        COMPL = "High"
    else:
        COMPL = "Undefined"  # Если ни одно из условий не выполнено

    return COMPL

In [ ]:
# Вводим начальные параметры для определения сложности данных:
DET = ((17, 17, 19, 19),(17, 17, 19, 19))   # (Data Element Type) количество неповторяемых уникальных полей данных
RET = ((1, 1, 3, 3),(1, 1, 3, 3))           # (Record Element Type) количество логических групп данных
print(f"При указанных выше значениях параметров DET и RET, сложность данных определяется как  {complexity(DET, RET)}")

При указанных выше значениях параметров DET и RET, сложность данных определяется как  Low


In [ ]:
# Оценка данных в невыровненных  функциональных точках (UFP) для внутренних логических файлов (ILFs) и внешних интерфейсных файлов (EIFs)
# Если complexity(DET, RET) = Low, то UFP_ILF = 7, если complexity(DET, RET) = Average, то UFP_ILF = 10, если complexity(DET, RET) = High, то UFP_ILF = 15;
# Если complexity(DET, RET) = Low, то UFP_EIF = 5, если complexity(DET, RET) = Average, то UFP_EIF = 7, если complexity(DET, RET) = High, то UFP_EIF = 10.
if complexity(DET, RET) == "Low":
    UFP_ILF = ((5.5, 6.5, 7.5, 8.5),(6.0, 6.5, 7.5, 8.0))
    UFP_EIF = ((3.5, 4.5, 5.5, 6.5),(4.0, 4.5, 5.5, 6.0))
elif complexity(DET, RET) == "Average":
    UFP_ILF = ((8.5, 9.5, 10.5, 11.5),(9.0, 9.5, 10.5, 11.0))
    UFP_EIF = ((5.5, 6.5, 7.5, 8.5),(6.0, 6.5, 7.5, 8.0))
elif complexity(DET, RET) == "High":
    UFP_ILF = ((13.5, 14.5, 15.5, 16.5),(14.0, 14.5, 15.5, 16.0))
    UFP_EIF = ((8.5, 9.5, 10.5, 11.5),(9.0, 9.5, 10.5, 11.0))
else:
    UFP_ILF = 0  # Значения по умолчанию, если сложность неопределена
    UFP_EIF = 0

In [ ]:
print(f"При указанных выше значениях параметров DET и RET, количество UFP(ILF) = {UFP_ILF}, UFP(EIF) = {UFP_EIF} невыровненных функциональных точек")

При указанных выше значениях параметров DET и RET, количество UFP(ILF) = ((5.5, 6.5, 7.5, 8.5), (6.0, 6.5, 7.5, 8.0)), UFP(EIF) = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0)) невыровненных функциональных точек


In [ ]:
# Функция расчета матрицы сложности внешних входных транзакций (EI)
def complexity1(DET1, FTR):
  # если DET1 < 5 и FTR < 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR < 2, то COMPL1 = Low; если DET1 > 15 и FTR < 2, то COMPL1 = Average;
  # если DET1 < 5 и FTR = 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR = 2, то COMPL1 = Average; если DET1 > 15 и FTR = 2, то COMPL1 = High;
  # если DET1 < 5 и FTR > 2, то COMPL1 = Average; если 5 <= DET1 <= 15 и FTR > 2, то COMPL1 = High; если DET1 > 15 и FTR > 2, то COMPL1 = High;
    # Присвоим значения из трапециевидных чисел
    ((x1, x2, x3, x4), (x5, x6, x7, x8)) = DET1
    ((y1, y2, y3, y4), (y5, y6, y7, y8)) = FTR
    mean_DET1 = (x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8) / 8
    mean_FTR = (y1 + y2 + y3 + y4 + y5 + y6 + y7 + y8) / 8


    if mean_DET1 < 5 and mean_FTR < 2:
        COMPL1 = "Low"
    elif 5 <= x3 <= 15 and mean_FTR < 2:
        COMPL1 = "Low"
    elif mean_DET1 > 15 and mean_FTR < 2:
        COMPL1 = "Average"
    elif mean_DET1 < 5 and mean_FTR == 2:
        COMPL1 = "Low"
    elif 5 <= mean_DET1 <= 15 and mean_FTR == 2:
        COMPL1 = "Average"
    elif mean_DET1 > 15 and mean_FTR == 2:
        COMPL1 = "High"
    elif mean_DET1 < 5 and mean_FTR > 2:
        COMPL1 = "Average"
    elif 5 <= mean_DET1 <= 15 and mean_FTR > 2:
        COMPL1 = "High"
    elif mean_DET1 > 15 and mean_FTR > 2:
        COMPL1 = "High"
    else:
        COMPL1 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено

    return COMPL1

In [ ]:
# Функция расчета матрицы сложности внешних выходных транзакций и внешних запросов (EO&EQ)
def complexity2(DET1, FTR):
  # если DET1 < 6 и FTR < 2, то COMPL2 = Low; если 6 <= DET1 <= 19 и FTR < 2, то COMPL2 = Low; если DET1 > 19 и FTR < 2, то COMPL2 = Average;
  # если DET1 < 6 и 2 <= FTR <= 3, то COMPL2 = Low; если 6 <= DET1 <= 19 и 2 <= FTR <= 3, то COMPL2 = Average; если DET1 > 19 и 2 <= FTR <= 3, то COMPL2 = High;
  # если DET1 < 6 и FTR > 3, то COMPL2 = Average; если 6 <= DET1 <= 19 и FTR > 3, то COMPL2 = High; если DET1 > 19 и FTR > 3, то COMPL2 = High;
    # Присвоим значения из трапециевидных чисел
    ((x1, x2, x3, x4), (x5, x6, x7, x8)) = DET1
    ((y1, y2, y3, y4), (y5, y6, y7, y8)) = FTR

    mean_DET1 = (x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8) / 8
    mean_FTR = (y1 + y2 + y3 + y4 + y5 + y6 + y7 + y8) / 8

 # Определение сложности на основе условий
    if mean_DET1 < 6 and mean_FTR < 2:
        COMPL2 = "Low"
    elif 6 <= mean_DET1 <= 19 and mean_FTR < 2:
        COMPL2 = "Low"
    elif mean_DET1 > 19 and mean_FTR < 2:
        COMPL2 = "Average"
    elif mean_DET1 < 6 and 2 <= mean_FTR <= 3:
        COMPL2 = "Low"
    elif 6 <= mean_DET1 <= 19 and 2 <= mean_FTR <= 3:
        COMPL2 = "Average"
    elif mean_DET1 > 19 and 2 <= mean_FTR <= 3:
        COMPL2 = "High"
    elif mean_DET1 < 6 and mean_FTR > 3:
        COMPL2 = "Average"
    elif 6 <= mean_DET1 <= 19 and mean_FTR > 3:
        COMPL2 = "High"
    elif mean_DET1 > 19 and mean_FTR > 3:
        COMPL2 = "High"
    else:
        COMPL2 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено
    return COMPL2

In [ ]:
# Вводим характеристики оценки сложности транзакций
DET1 = ((17, 17, 19, 19),(17, 17, 19, 19))  # (Data Element Type) количество неповторяемых уникальных полей данных
FTR = ((3, 3, 5, 5),(3, 3, 5, 5))           # (File Type Referenced) количество файлов (информационных объектов) типа ILF и/или EIF, модифицируемых или считываемых в транзакции
print(f"При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как {complexity1(DET1, FTR)},\n"
f"сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как {complexity2(DET1, FTR)}")

При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как High,
сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как High


In [ ]:
# Оценка сложности транзакций в невыровненных  функциональных точках (UFP)
# Если complexity1(DET1, FTR) = Low, то UFP_EI = 3, если complexity1(DET1, FTR) = Average, то UFP_EI = 4, если complexity1(DET1, FTR) = High, то UFP_EI = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EQ = 3, если complexity2(DET1, FTR) = Average, то UFP_EQ = 4, если complexity2(DET1, FTR) = High, то UFP_EQ = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EO = 4, если complexity2(DET1, FTR) = Average, то UFP_EO = 5, если complexity2(DET1, FTR) = High, то UFP_EO = 7;
if complexity1(DET1, FTR) == "Low":
    UFP_EI = ((1.5, 2.5, 3.5, 4.5),(2.0, 2.5, 3.5, 4.0))
elif complexity1(DET1, FTR) == "Average":
    UFP_EI = ((2.5, 3.5, 4.5, 5.5),(3.0, 3.5, 4.5, 5.0))
elif complexity1(DET1, FTR) == "High":
    UFP_EI = ((4.5, 5.5, 6.5, 7.5),(5.0, 5.5, 6.5, 7.0))
else:
    UFP_EI = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EQ = ((1.5, 2.5, 3.5, 4.5),(2.0, 2.5, 3.5, 4.0))
elif complexity2(DET1, FTR) == "Average":
    UFP_EQ = ((2.5, 3.5, 4.5, 5.5),(3.0, 3.5, 4.5, 5.0))
elif complexity2(DET1, FTR) == "High":
    UFP_EQ = ((4.5, 5.5, 6.5, 7.5),(5.0, 5.5, 6.5, 7.0))
else:
    UFP_EQ = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EO = ((2.5, 3.5, 4.5, 5.5),(3.0, 3.5, 4.5, 5.0))
elif complexity2(DET1, FTR) == "Average":
    UFP_EO = ((3.5, 4.5, 5.5, 6.5),(4.0, 4.5, 5.5, 6.0))
elif complexity2(DET1, FTR) == "High":
    UFP_EO = ((5.5, 6.5, 7.5, 8.5),(6.0, 6.5, 7.5, 8.0))
else:
    UFP_EO = None  # Значение по умолчанию, если не определено

In [ ]:
print(f"При указанных выше значениях параметров DET1 и FTR, количество UFP(EI)= {UFP_EI}, UFP(EQ)= {UFP_EQ}, UFP(EO)= {UFP_EO} невыровненных функциональных точек")

При указанных выше значениях параметров DET1 и FTR, количество UFP(EI)= ((4.5, 5.5, 6.5, 7.5), (5.0, 5.5, 6.5, 7.0)), UFP(EQ)= ((4.5, 5.5, 6.5, 7.5), (5.0, 5.5, 6.5, 7.0)), UFP(EO)= ((5.5, 6.5, 7.5, 8.5), (6.0, 6.5, 7.5, 8.0)) невыровненных функциональных точек


In [ ]:
# Расчет количества невыровненных функциональных точек
# UFP = UFP_ILF + UFP_EIF + UFP_EI + UFP_EO + UFP_EQ

def calculate_UFP(*params):
    UFP = params[0]
    for param in params[1:]:
        UFP = add_intuitionistic_trapezoidal_fuzzy_numbers(UFP, param)
    return UFP

# Вычисляем суммарное количество невыровненных функциональных точек UFP
UFP_result = calculate_UFP(UFP_ILF, UFP_EIF, UFP_EI, UFP_EO, UFP_EQ)

print(f"При рассчитанных выше значениях, суммарная оценка количества невыровненных функциональных точек UFP принимает значение {UFP_result}")

При рассчитанных выше значениях, суммарная оценка количества невыровненных функциональных точек UFP принимает значение ((23.5, 28.5, 33.5, 38.5), (26.0, 28.5, 33.5, 36.0))


In [ ]:
# Определение значения фактора выравнивания (FAV)
# TDI = DI1 + DI2 + DI3 + DI4 + DI5 + DI6 + DI7 + DI8 + DI9 + DI10 + DI11 + DI12 + DI13 + DI14

def calculate_TDI(*params):
    TDI = params[0]
    for param in params[1:]:
        TDI = add_intuitionistic_trapezoidal_fuzzy_numbers(TDI, param)
    return TDI

In [ ]:
# Определение параметров фактора выравнивания (FAV)
DI1 = ((2.5, 3.5, 4.5, 5.5), (3.0, 3.5, 4.5, 5.0))   # Обмен данными, показатель от 0 до 5 включительно
DI2 = ((1.5, 2.5, 3.5, 4.5), (2.0, 2.5, 3.5, 4.0))   # Распределенная обработка данных, показатель от 0 до 5 включительно
DI3 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Производительность, показатель от 0 до 5 включительно
DI4 = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))   # Ограничения по аппаратным ресурсам, показатель от 0 до 5 включительно
DI5 = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Транзакционная нагрузка, показатель от 0 до 5 включительно
DI6 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Интенсивность взаимодействия с пользователем, показатель от 0 до 5 включительно
DI7 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Эргономика (эффективность работы конечных пользователей), показатель от 0 до 5 включительно
DI8 = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Интенсивность изменения данных (ILF) пользователями, показатель от 0 до 5 включительно
DI9 = ((2.5, 3.5, 4.5, 5.5), (3.0, 3.5, 4.5, 5.0))   # Сложность обработки, показатель от 0 до 5 включительно
DI10 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))  # Повторное использование, показатель от 0 до 5 включительно
DI11 = ((1.5, 2.5, 3.5, 4.5), (2.0, 2.5, 3.5, 4.0))  # Удобство инсталляции, показатель от 0 до 5 включительно
DI12 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))  # Удобство администрирования, показатель от 0 до 5 включительно
DI13 = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))  # Портируемость, показатель от 0 до 5 включительно
DI14 = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))  # Гибкость, показатель от 0 до 5 включительно

# Вычисляем суммарный эффект TDI
TDI = calculate_TDI(DI1, DI2, DI3, DI4, DI5, DI6, DI7, DI8, DI9, DI10, DI11, DI12, DI13, DI14)

print(f"При вышеуказанных системных параметрах DI1-DI14, суммарный эффект TDI принимает значение {TDI}")

При вышеуказанных системных параметрах DI1-DI14, суммарный эффект TDI принимает значение ((25.5, 36.0, 48.0, 62.0), (30.0, 36.0, 48.0, 55.0))


In [ ]:
# Расчет значения фактора выравнивания VAF
# VAF = (TDI * 0.01) + 0.65
def multiply_fuzzy_number_by_constant(fuzzy_number, constant):
    # Умножение нечеткого числа на константу
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    if constant < 0:
        # Умножение всех координат на константу в обратном порядке
        new_X = (
            (x4 * constant, x3 * constant, x2 * constant, x1 * constant),
            (x8 * constant, x7 * constant, x6 * constant, x5 * constant)
        )
    else:
        # Умножение всех координат на константу в обычном порядке
        new_X = (
            (x1 * constant, x2 * constant, x3 * constant, x4 * constant),
            (x5 * constant, x6 * constant, x7 * constant, x8 * constant)
        )
    return new_X

def add_constant_to_fuzzy_number(X, constant):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    # Прибавление константы ко всем координатам
    new_X = (
        (x1 + constant, x2 + constant, x3 + constant, x4 + constant),
        (x5 + constant, x6 + constant, x7 + constant, x8 + constant)
    )
    return new_X

# Умножаем TDI на 0.01
TDI_multiplied = multiply_fuzzy_number_by_constant(TDI, 0.01)

# Добавляем 0.65 к результату
VAF = add_constant_to_fuzzy_number(TDI_multiplied, 0.65)

In [ ]:
print(f"При рассчитанном выше суммарном эффекте системных характеристик TDI, фактор выравнивания VAF принимает значение {VAF}")

При рассчитанном выше суммарном эффекте системных характеристик TDI, фактор выравнивания VAF принимает значение ((0.905, 1.01, 1.13, 1.27), (0.95, 1.01, 1.13, 1.2000000000000002))


In [ ]:
# Расчет количества выровненных функциональных точек (AFP)
# AFP = UFP * VAF
def multiply_intuitionistic_trapezoidal_fuzzy_numbers(X, Y):
    # Распаковка параметров интервальных трапециевидных чисел 2 типа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    (y1, y2, y3, y4), (y5, y6, y7, y8) = Y

    # Вычисление координат для произведения с округлением
    z1 = round(x2 * y1 - x2 * y2 + x1 * y2, 2)
    z2 = round(x2 * y2, 2)
    z3 = round(x3 * y3, 2)
    z4 = round(x3 * y4 - x3 * y3 + y3 * x4, 2)

    z5 = round(x6 * y5 - x6 * y6 + x5 * y6, 2)
    z6 = round(x6 * y6, 2)
    z7 = round(x7 * y7, 2)
    z8 = round(x7 * y8 - x7 * y7 + y7 * x8, 2)

    return ((z1, z2, z3, z4), (z5, z6, z7, z8))

# Умножение интервальных трапециевидных чисел 2 типа
AFP = multiply_intuitionistic_trapezoidal_fuzzy_numbers(UFP_result, VAF)

In [ ]:
print(f"При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение {AFP} выровненных функциональных точек")

При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение ((20.74, 28.79, 37.85, 48.2), (24.55, 28.79, 37.85, 43.02)) выровненных функциональных точек


Для перехода от нечетких значений к четким применим операцию альфа-среза. В результате получим четкий интервал (отрезок) значений из области определения нечеткого трапециевидного числа 2-го типа, который будет соответствовать единственному значению функции принадлежности, заданному уровнем альфа-среза.

In [ ]:
def alpha_cut(fuzzy_number, alpha):
    # Распаковка параметров нечеткого числа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number

    # Вычисление концов верхнего интервала альфа-среза
    upper_start = alpha * x2 + (1 - alpha) * x1
    upper_end = alpha * x3 + (1 - alpha) * x4

    # Вычисление концов нижнего интервала альфа-среза
    lower_start = alpha * x6 + (1 - alpha) * x5
    lower_end = alpha * x7 + (1 - alpha) * x8

    # Округляем значения до 3 знаков после запятой
    upper_start = round(upper_start, 3)
    upper_end = round(upper_end, 3)
    lower_start = round(lower_start, 3)
    lower_end = round(lower_end, 3)

    # Возвращаем альфа-срез в виде нечеткого числа
    return ((upper_start, upper_end), (lower_start, lower_end))

Зададим уровень альфа-среза равным 0.8. Значение альфа-среза - это уровень уверенности стейкхолдеров в полученной оценке итогового результата моделирования. Левая и права граница интервала (отрезка, являющегося результатом применения альфа-среза) - это минимальное (левая граница) и максимальное (правая граница) значения, которые может принимать результат моделирования с данной степенью уверенности.

In [ ]:
# Вычисление альфа-среза
alpha = 0.8
alpha_cut_result = alpha_cut(AFP, alpha)
print(f"Альфа-срез при альфа = {alpha} для AFP {AFP} равен {alpha_cut_result}")

Альфа-срез при альфа = 0.8 для AFP ((20.74, 28.79, 37.85, 48.2), (24.55, 28.79, 37.85, 43.02)) равен ((27.18, 39.92), (27.942, 38.884))


Другими словами, с 80% уверенностью можно утверждать, что результат применения данной модели составит от 27.18 до 39.92 выровненных функциональных точек в верхней функции принадлежности и от 27.94 до 38.84 выровненных функциональных точек в нижней функции принадлежности.

Для приведения интервальных оценок к точечным результатам применяются методы усреднения, например, центроид системы двух точек, которым является середина отрезка, соединяющего данные точки, т.е. среднее арифметическое левого и правого значения его координат (среднее минимума и максимума по оси абсцисс).

In [ ]:
def centroid(alpha_cut_result):
    # Распаковка верхнего и нижнего отрезков альфа-среза
    (upper_start, upper_end), (lower_start, lower_end) = alpha_cut_result

    # Расчет среднего значения
    central_upper = round((upper_start + upper_end) / 2, 3)
    central_lower = round((lower_start + lower_end) / 2, 3)

    # Возвращаем результат в нужном формате
    return (central_upper, central_lower)

alpha_cut_result = alpha_cut(AFP, alpha)
central_result = centroid(alpha_cut_result)

print(f"Усредненные значения для AFP {AFP} при альфа = {alpha} равны {central_result}")


Усредненные значения для AFP ((20.74, 28.79, 37.85, 48.2), (24.55, 28.79, 37.85, 43.02)) при альфа = 0.8 равны (33.55, 33.413)


Усредненное (точечное) четкое значение результата моделирования составляет 33,55 выровненных функциональных точки по верхней функции принадлежности и 33,41 - по нижней.

In [ ]:
# Вычисляем среднее арифметическое усредненных значений
AFP_final = calculate_average(central_result)

print(f"Среднее значение трудоемкости по нечеткой модели составляет {AFP_final} выровненных функциональных точки")

Среднее значение трудоемкости по нечеткой модели составляет 33.481 выровненных функциональных точки


Итоговое усредненное четкое значение результата моделирования составляет 33,48 выровненных функциональных точки

# Нечеткая Модель *FPA*. Применение колеблющихся нечетких чисел

In [ ]:
# Функция для обработки результата - исключение повторов и упорядочивание по возрастанию значений функции принадлежности
def process_fuzzy_result(fuzzy_result):
    # Распаковка результата
    x_value, *parameters = fuzzy_result

    # Исключение повторяющихся значений и упорядочение по возрастанию
    unique_parameters = sorted(set(parameters))

    # Формирование нового кортежа с уникальными значениями
    processed_result = (x_value, *unique_parameters)

    return processed_result

In [ ]:
# Функция для сложения дискретных колеблющихся нечетких чисел
def add_discrete_fuzzy_numbers(X, Y):
    x_value, *x_parameters = X
    y_value, *y_parameters = Y
    result_parameters = []

    for xi in x_parameters:
        for yj in y_parameters:
            zij = round(xi + yj - xi * yj, 2)
            result_parameters.append(zij)

    Z = round(x_value + y_value, 2)
    return (Z, *result_parameters)

In [ ]:
# Определение сложности данных
def complexity(DET, RET):
# Извлечение значения из дискретного колеблющегося нечеткого числа
    x_value = DET[0]  # Первое значение в кортеже DET
    y_value = RET[0]  # Первое значение в кортеже RET

    # Используем условия для определения сложности с учетом DET_mid_high и RET_mid_high
    if x_value < 20 and  y_value == 1:
        COMPL = "Low"
    elif 20 <= x_value <= 50 and y_value == 1:
        COMPL = "Low"
    elif x_value > 50 and y_value == 1:
        COMPL = "Average"
    elif x_value < 20 and 2 <= y_value <= 5:
        COMPL = "Low"
    elif 20 <= x_value <= 50 and 2 <= y_value <= 5:
        COMPL = "Average"
    elif x_value > 50 and 2 <= y_value <= 5:
        COMPL = "High"
    elif x_value < 20 and y_value > 5:
        COMPL = "Average"
    elif 20 <= x_value <= 50 and y_value > 5:
        COMPL = "High"
    elif x_value > 50 and y_value > 5:
        COMPL = "High"
    else:
        COMPL = "Undefined"  # Если ни одно из условий не выполнено

    return COMPL

In [ ]:
#Вводим начальные параметры для определения сложности данных:
DET = (18, 0.8, 0.9)     # (Data Element Type) количество неповторяемых уникальных полей данных
RET = (2, 0.7, 0.8)      # (Record Element Type) количество логических групп данных
print(f"При указанных выше значениях параметров DET и RET, сложность данных определяется как  {complexity(DET, RET)}")

При указанных выше значениях параметров DET и RET, сложность данных определяется как  Low


In [ ]:
# Оценка данных в невыровненных  функциональных точках (UFP) для внутренних логических файлов (ILFs) и внешних интерфейсных файлов (EIFs)
# Если complexity(DET, RET) = Low, то UFP_ILF = 7, если complexity(DET, RET) = Average, то UFP_ILF = 10, если complexity(DET, RET) = High, то UFP_ILF = 15;
# Если complexity(DET, RET) = Low, то UFP_EIF = 5, если complexity(DET, RET) = Average, то UFP_EIF = 7, если complexity(DET, RET) = High, то UFP_EIF = 10.
if complexity(DET, RET) == "Low":
    UFP_ILF = (7, 0.5, 0.6)
    UFP_EIF = (5, 0.5, 0.6)
elif complexity(DET, RET) == "Average":
    UFP_ILF = (10, 0.5, 0.6)
    UFP_EIF = (7, 0.5, 0.6)
elif complexity(DET, RET) == "High":
    UFP_ILF = (15, 0.5, 0.6)
    UFP_EIF = (10, 0.5, 0.6),
else:
    UFP_ILF = 0  # Значения по умолчанию, если сложность неопределена
    UFP_EIF = 0

In [ ]:
print(f"При указанных выше значениях параметров DET и RET, количество UFP(ILF) = {UFP_ILF}, UFP(EIF)= {UFP_EIF} невыровненных функциональных точек")

При указанных выше значениях параметров DET и RET, количество UFP(ILF) = (7, 0.5, 0.6), UFP(EIF)= (5, 0.5, 0.6) невыровненных функциональных точек


In [ ]:
# Функция расчета матрицы сложности внешних входных транзакций (EI)
def complexity1(DET1, FTR):
  # если DET1 < 5 и FTR < 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR < 2, то COMPL1 = Low; если DET1 > 15 и FTR < 2, то COMPL1 = Average;
  # если DET1 < 5 и FTR = 2, то COMPL1 = Low; если 5 <= DET1 <= 15 и FTR = 2, то COMPL1 = Average; если DET1 > 15 и FTR = 2, то COMPL1 = High;
  # если DET1 < 5 и FTR > 2, то COMPL1 = Average; если 5 <= DET1 <= 15 и FTR > 2, то COMPL1 = High; если DET1 > 15 и FTR > 2, то COMPL1 = High;
    # Присвоим значения из колеблющихся нечетких чисел
    x_value = DET1[0]  # Первое значение в кортеже DET1
    y_value = FTR[0]   # Первое значение в кортеже FTR

    if x_value < 5 and y_value < 2:
        COMPL1 = "Low"
    elif 5 <= x_value <= 15 and y_value < 2:
        COMPL1 = "Low"
    elif x_value > 15 and y_value < 2:
        COMPL1 = "Average"
    elif x_value < 5 and y_value == 2:
        COMPL1 = "Low"
    elif 5 <= x_value <= 15 and y_value == 2:
        COMPL1 = "Average"
    elif x_value > 15 and y_value == 2:
        COMPL1 = "High"
    elif x_value < 5 and y_value > 2:
        COMPL1 = "Average"
    elif 5 <= x_value <= 15 and y_value > 2:
        COMPL1 = "High"
    elif x_value > 15 and y_value > 2:
        COMPL1 = "High"
    else:
        COMPL1 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено

    return COMPL1

In [ ]:
# Функция расчета матрицы сложности внешних выходных транзакций и внешних запросов (EO&EQ)
def complexity2(DET1, FTR):
  # если DET1 < 6 и FTR < 2, то COMPL2 = Low; если 6 <= DET1 <= 19 и FTR < 2, то COMPL2 = Low; если DET1 > 19 и FTR < 2, то COMPL2 = Average;
  # если DET1 < 6 и 2 <= FTR <= 3, то COMPL2 = Low; если 6 <= DET1 <= 19 и 2 <= FTR <= 3, то COMPL2 = Average; если DET1 > 19 и 2 <= FTR <= 3, то COMPL2 = High;
  # если DET1 < 6 и FTR > 3, то COMPL2 = Average; если 6 <= DET1 <= 19 и FTR > 3, то COMPL2 = High; если DET1 > 19 и FTR > 3, то COMPL2 = High;
    # Присвоим значения из колеблющихся нечетких чисел
    x_value = DET1[0]  # Первое значение в кортеже DET1
    y_value = FTR[0]   # Первое значение в кортеже FTR
 # Определение сложности на основе условий
    if x_value < 6 and y_value < 2:
        COMPL2 = "Low"
    elif 6 <= x_value <= 19 and y_value < 2:
        COMPL2 = "Low"
    elif x_value > 19 and y_value < 2:
        COMPL2 = "Average"
    elif x_value < 6 and 2 <= y_value <= 3:
        COMPL2 = "Low"
    elif 6 <= x_value <= 19 and 2 <= y_value <= 3:
        COMPL2 = "Average"
    elif x_value > 19 and 2 <= y_value <= 3:
        COMPL2 = "High"
    elif x_value < 6 and y_value > 3:
        COMPL2 = "Average"
    elif 6 <= x_value <= 19 and y_value > 3:
        COMPL2 = "High"
    elif x_value > 19 and y_value > 3:
        COMPL2 = "High"
    else:
        COMPL2 = "Undefined"  # Значение по умолчанию, если ни одно из условий не выполнено
    return COMPL2

In [ ]:
# Вводим характеристики оценки сложности транзакций
DET1 = (18, 0.8, 0.9)  # (Data Element Type) количество неповторяемых уникальных полей данных
FTR = (4, 0.7, 0.8)    # (File Type Referenced) количество файлов (информационных объектов) типа ILF и/или EIF, модифицируемых или считываемых в транзакции
print(f"При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как {complexity1(DET1, FTR)},\n"
f"сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как {complexity2(DET1, FTR)}")

При указанных выше значениях параметров DET1 и FTR, сложность внешних входных транзакций (EI) определяется как High,
сложность внешних выходных транзакций и внешних запросов (EO&EQ) определяется как High


In [ ]:
# Оценка сложности транзакций в невыровненных  функциональных точках (UFP)
# Если complexity1(DET1, FTR) = Low, то UFP_EI = 3, если complexity1(DET1, FTR) = Average, то UFP_EI = 4, если complexity1(DET1, FTR) = High, то UFP_EI = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EQ = 3, если complexity2(DET1, FTR) = Average, то UFP_EQ = 4, если complexity2(DET1, FTR) = High, то UFP_EQ = 6;
# Если complexity2(DET1, FTR) = Low, то UFP_EO = 4, если complexity2(DET1, FTR) = Average, то UFP_EO = 5, если complexity2(DET1, FTR) = High, то UFP_EO = 7;
if complexity1(DET1, FTR) == "Low":
    UFP_EI = (3, 0.5, 0.6)
elif complexity1(DET1, FTR) == "Average":
    UFP_EI = (4, 0.5, 0.6)
elif complexity1(DET1, FTR) == "High":
    UFP_EI = (6, 0.5, 0.6)
else:
    UFP_EI = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EQ = (3, 0.5, 0.6)
elif complexity2(DET1, FTR) == "Average":
    UFP_EQ = (4, 0.5, 0.6)
elif complexity2(DET1, FTR) == "High":
    UFP_EQ = (6, 0.5, 0.6)
else:
    UFP_EQ = None  # Значение по умолчанию, если не определено

if complexity2(DET1, FTR) == "Low":
    UFP_EO = (4, 0.5, 0.6)
elif complexity2(DET1, FTR) == "Average":
    UFP_EO = (5, 0.5, 0.6)
elif complexity2(DET1, FTR) == "High":
    UFP_EO = (7, 0.5, 0.6)
else:
    UFP_EO = None  # Значение по умолчанию, если не определено

In [ ]:
print(f"При указанных выше значениях параметров DET1 и FTR, количество UFP(EI) = {UFP_EI}, UFP(EQ) = {UFP_EQ}, UFP(EO) = {UFP_EO} невыровненных функциональных точек")

При указанных выше значениях параметров DET1 и FTR, количество UFP(EI) = (6, 0.5, 0.6), UFP(EQ) = (6, 0.5, 0.6), UFP(EO) = (7, 0.5, 0.6) невыровненных функциональных точек


In [ ]:
# Список всех нечетких чисел
fuzzy_numbers = [UFP_ILF, UFP_EIF, UFP_EI, UFP_EQ, UFP_EO]

# Начинаем с первого нечеткого числа
current_sum = fuzzy_numbers[0]

# Поочередно складываем все нечеткие числа
for fuzzy_number in fuzzy_numbers[1:]:
    current_sum = add_discrete_fuzzy_numbers(current_sum, fuzzy_number)

# Вычисляем суммарное количество невыровненных функциональных точек UFP
UFP_result = current_sum

# Вывод результата
print(f"Итоговая сумма UFP: {UFP_result}")  # Вывод суммы


Итоговая сумма UFP: (31, 0.97, 0.98, 0.97, 0.98, 0.97, 0.98, 0.98, 0.98, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.99, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.99, 0.98, 0.98, 0.98, 0.99, 0.98, 0.99, 0.99, 0.99)


In [ ]:
# Дополнение к коду для обработки результата
UFP_processed_result = process_fuzzy_result(UFP_result)

# Вывод обработанного результата
print(f"Обработанный результат UFP: {UFP_processed_result}")

Обработанный результат UFP: (31, 0.97, 0.98, 0.99)


In [ ]:
# Определение значения фактора выравнивания (FAV)
# TDI = DI1 + DI2 + DI3 + DI4 + DI5 + DI6 + DI7 + DI8 + DI9 + DI10 + DI11 + DI12 + DI13 + DI14

# Определение параметров фактора выравнивания (FAV)
DI1 = (4, 0.2, 0.3)   # Обмен данными, показатель от 0 до 5 включительно
DI2 = (3, 0.2, 0.3)   # Распределенная обработка данных, показатель от 0 до 5 включительно
DI3 = (5, 0.2, 0.3)   # Производительность, показатель от 0 до 5 включительно
DI4 = (1, 0.2, 0.3)   # Ограничения по аппаратным ресурсам, показатель от 0 до 5 включительно
DI5 = (0, 0.2, 0.3)   # Транзакционная нагрузка, показатель от 0 до 5 включительно
DI6 = (5, 0.2, 0.3)   # Интенсивность взаимодействия с пользователем, показатель от 0 до 5 включительно
DI7 = (5, 0.2, 0.3)   # Эргономика (эффективность работы конечных пользователей), показатель от 0 до 5 включительно
DI8 = (0, 0.2, 0.3)   # Интенсивность изменения данных (ILF) пользователями, показатель от 0 до 5 включительно
DI9 = (4, 0.2, 0.3)   # Сложность обработки, показатель от 0 до 5 включительно
DI10 = (5, 0.2, 0.3)  # Повторное использование, показатель от 0 до 5 включительно
DI11 = (3, 0.2, 0.3)  # Удобство инсталляции, показатель от 0 до 5 включительно
DI12 = (5, 0.2, 0.3)  # Удобство администрирования, показатель от 0 до 5 включительно
DI13 = (1, 0.2, 0.3)  # Портируемость, показатель от 0 до 5 включительно
DI14 = (1, 0.2, 0.3)  # Гибкость, показатель от 0 до 5 включительно

# Список всех нечетких чисел
fuzzy_numbers = [DI1, DI2, DI3, DI4, DI5, DI6, DI7, DI8, DI9, DI10, DI11, DI12, DI13, DI14]

# Начинаем с первого нечеткого числа
current_sum = fuzzy_numbers[0]

# Поочередно складываем все нечеткие числа
for fuzzy_number in fuzzy_numbers[1:]:
    current_sum = add_discrete_fuzzy_numbers(current_sum, fuzzy_number)

# Вычисляем суммарное количество невыровненных функциональных точек UFP
TDI = current_sum

# Вывод результата
print(f"Итоговая сумма TDI: {TDI}")

Итоговая сумма TDI: (42, 0.95, 0.96, 0.96, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.96, 0.97, 0.97, 0.97, 0.97, 0.97, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.97, 0.97, 0.9

In [ ]:
# Дополнение к коду для обработки результата
TDI_processed_result = process_fuzzy_result(TDI)

# Вывод обработанного результата
print(f"Обработанный результат TDI: {TDI_processed_result}")

Обработанный результат TDI: (42, 0.95, 0.96, 0.97, 0.98, 0.99)


In [ ]:
# Расчет значения фактора выравнивания VAF
# VAF = (TDI * 0.01) + 0.65
# Функция для умножения дискретного колеблющегося нечеткого числа на константу
def multiply_fuzzy_number_with_constant(X, A):
    x, *parameters = X
    Z = round(A * x, 3)
    new_parameters = [round(1 - (1 - param) ** A, 2) for param in parameters]
    return (round(Z, 3), *new_parameters)

def add_fuzzy_number_with_constant(X, A):
    # Распаковка параметров нечеткого числа
    x, *membership_degrees = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = x + A  # Сумма значения X и константы A

    # Параметры (степени принадлежности) остаются без изменений
    return (round(Z, 3), *membership_degrees)


# Умножаем TDI на 0.01
multiplied_result = multiply_fuzzy_number_with_constant(TDI_processed_result, 0.01)

# Теперь прибавляем 0.65 к результату
VAF = add_fuzzy_number_with_constant(multiplied_result, 0.65)

# Вывод результата VAF
print(f"Значение VAF: {VAF}")

Значение VAF: (1.07, 0.03, 0.03, 0.03, 0.04, 0.05)


In [ ]:
# Дополнение к коду для обработки результата
VAF_processed_result = process_fuzzy_result(VAF)

# Вывод обработанного результата
print(f"Обработанный результат VAF: {VAF_processed_result}")

Обработанный результат VAF: (1.07, 0.03, 0.04, 0.05)


Так как при умножении нечеткого колеблющегося числа на константу значения константы становятся показателями степеней, в которую возводятся значения *HFE*, то при возведении значений функции принадлежности в степень 0.01 получаются значения, очень близкие к 1. Поскольку по формуле далее они вычитаются из 1, то итоговые значения степеней принадлежности *VAF* очень близки к нулю, что в дальнейшем приводит к очень низким показателям степеней принадлежности итогового расчетного результата по модели.

In [ ]:
def multiply_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X  # Извлекаем значение и параметры X
    y_value, *y_parameters = Y  # Извлекаем значение и параметры Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for x_param in x_parameters:
        for y_param in y_parameters:
            # Вычисление параметров для Z
            z_param = round(x_param * y_param, 2)
            result_parameters.append(z_param)

    # Вычисление значения Z
    Z_value = round(x_value * y_value, 2)  # Произведение значений X и Y

    return (Z_value, *result_parameters)

# Умножение колеблющихся нечетких чисел
AFP = multiply_discrete_fuzzy_numbers(UFP_processed_result, VAF_processed_result)

In [ ]:
print(f"При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение {AFP} выровненных функциональных точек")

При рассчитанных выше параметрах, оценка проекта (новая функциональность) AFP принимает значение (33.17, 0.03, 0.04, 0.05, 0.03, 0.04, 0.05, 0.03, 0.04, 0.05) выровненных функциональных точек


In [ ]:
# Дополнение к коду для обработки результата
AFP_processed_result = process_fuzzy_result(AFP)

# Вывод обработанного результата
print(f"Обработанный результат AFP: {AFP_processed_result}")

Обработанный результат AFP: (33.17, 0.03, 0.04, 0.05)


Вывод: колеблющиеся нечеткие множества не совсем подходят для использования в данной модели, так как большое количество нечетких слагаемых (со степенями принадлежности выше 0.5) при суммировании приводит к значениям степеней принадлежности результирующего *HFE* , близким к 1, а константы (если они близки к 0), при умножении на них *HFE* очень сильно cнижают итоговые значения степеней принадлежности результата. В итоге степень принадлежности расчетного параметра либо очень большая (около, либо равна 1), либо очень маленькая (около, либо равна 0) и ее значение наглядно не отражает уровни степеней принадлежности входных данных.


# Модель *COCOMO II*

**Четкая модель *COCOMO II* (предварительная оценка на начальной стадии проекта при однокомпонентной разработке, используются 7 факторов масштаба *FSj*. У детальной оценки после проработки архитектуры - 17 факторов масштаба *FSj*)**

In [ ]:
def SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT):
# если PREC = "Very Low", то PREC1 = 6.20, если PREC = "Low", то PREC1 = 4.96, если PREC = "Nominal", то PREC1 = 3,72, если PREC = "High", то PREC1 = 2.48, если PREC = "Very High", то PREC1 = 1.24, если PREC = "Extra High", то PREC1 = 0;
# если FLEX = "Very Low", то FLEX1 = 5.07, если FLEX = "Low", то FLEX1 = 4.05, если FLEX = "Nominal", то FLEX1 = 3,04, если FLEX = "High", то FLEX1 = 2.03, если FLEX = "Very High", то FLEX1 = 1.01, если FLEX = "Extra High", то FLEX1 = 0;
# если RESL = "Very Low", то RESL1 = 7.07, если RESL = "Low", то RESL1 = 5.65, если RESL = "Nominal", то RESL1 = 4,24, если RESL = "High", то RESL1 = 2.83, если RESL = "Very High", то RESL1 = 1.41, если RESL = "Extra High", то RESL1 = 0;
# если TEAM = "Very Low", то TEAM1 = 5.48, если TEAM = "Low", то TEAM1 = 4.38, если TEAM = "Nominal", то TEAM1 = 3,29, если TEAM = "High", то TEAM1 = 2.19, если TEAM = "Very High", то TEAM1 = 1.10, если TEAM = "Extra High", то TEAM1 = 0;
# если PMAT = "Very Low", то PMAT1 = 7.80, если PMAT = "Low", то PMAT1 = 6.24, если PMAT = "Nominal", то PMAT1 = 4,68, если PMAT = "High", то PMAT1 = 3.12, если PMAT = "Very High", то PMAT1 = 1.56, если PMAT = "Extra High", то PMAT1 = 0;
# Определение значений для PREC1
    if PREC == "Very Low":
        PREC1 = 6.20
    elif PREC == "Low":
        PREC1 = 4.96
    elif PREC == "Nominal":
        PREC1 = 3.72
    elif PREC == "High":
        PREC1 = 2.48
    elif PREC == "Very High":
        PREC1 = 1.24
    elif PREC == "Extra High":
        PREC1 = 0.00

    # Определение значений для FLEX1
    if FLEX == "Very Low":
        FLEX1 = 5.07
    elif FLEX == "Low":
        FLEX1 = 4.05
    elif FLEX == "Nominal":
        FLEX1 = 3.04
    elif FLEX == "High":
        FLEX1 = 2.03
    elif FLEX == "Very High":
        FLEX1 = 1.01
    elif FLEX == "Extra High":
        FLEX1 = 0.00

    # Определение значений для RESL1
    if RESL == "Very Low":
        RESL1 = 7.07
    elif RESL == "Low":
        RESL1 = 5.65
    elif RESL == "Nominal":
        RESL1 = 4.24
    elif RESL == "High":
        RESL1 = 2.83
    elif RESL == "Very High":
        RESL1 = 1.41
    elif RESL == "Extra High":
        RESL1 = 0.00

    # Определение значений для TEAM1
    if TEAM == "Very Low":
        TEAM1 = 5.48
    elif TEAM == "Low":
        TEAM1 = 4.38
    elif TEAM == "Nominal":
        TEAM1 = 3.29
    elif TEAM == "High":
        TEAM1 = 2.19
    elif TEAM == "Very High":
        TEAM1 = 1.10
    elif TEAM == "Extra High":
        TEAM1 = 0.00

    # Определение значений для PMAT1
    if PMAT == "Very Low":
        PMAT1 = 7.80
    elif PMAT == "Low":
        PMAT1 = 6.24
    elif PMAT == "Nominal":
        PMAT1 = 4.68
    elif PMAT == "High":
        PMAT1 = 3.12
    elif PMAT == "Very High":
        PMAT1 = 1.56
    elif PMAT == "Extra High":
        PMAT1 = 0.00
    SF_summ = PREC1 + FLEX1 + RESL1 + TEAM1 + PMAT1
    return SF_summ

In [ ]:
# Ввод факторов масштаба. Варианты оценки: "Very Low", "Low", "Nominal", "High", "Very High", "Extra High"
PREC = "Nominal"    # Прецендентность, наличие опыта аналогичных разработок
FLEX = "Low"        # Гибкость процесса разработки
RESL = "High"       # Архитектура и разрешение рисков
TEAM = "Very Low"   # Сработанность команды
PMAT = "Extra High" # Зрелость процессов
SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT)
print(f"При вышеуказанных значениях факторов масштаба, показатель SFj принимает значение {SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT)}")

При вышеуказанных значениях факторов масштаба, показатель SFj принимает значение 16.08


In [ ]:
E = round(0.91 + 0.01 * SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT), 2)

In [ ]:
print(f"При вышеуказанных значениях факторов масштаба, показатель E принимает значение {E}")

При вышеуказанных значениях факторов масштаба, показатель E принимает значение 1.07


In [ ]:
def EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED):
# если PERS = "Extra Low", то PERS1 = 2.12, если PERS = "Very Low", то PERS1 = 1.62, если PERS = "Low", то PERS1 = 1,26, если PERS = "Nominal", то PERS1 = 1.00, если PERS = "High", то PERS1 = 0.83, если PERS = "Very High", то PERS1 = 0.63, если PERS = "Extra High", то PERS1 = 0.5;
# если RCPX = "Extra Low", то RCPX1 = 0.49, если RCPX = "Very Low", то RCPX1 = 0.60, если RCPX = "Low", то RCPX1 = 0,83, если RCPX = "Nominal", то RCPX1 = 1.00, если RCPX = "High", то RCPX1 = 1.33, если RCPX = "Very High", то RCPX1 = 1.91, если RCPX = "Extra High", то RCPX1 = 2.72;
# если RUSE = "Low", то RUSE1 = 0,95, если RUSE = "Nominal", то RUSE1 = 1.00, если RUSE = "High", то RUSE1 = 1.07, если RUSE = "Very High", то RUSE1 = 1.15, если RUSE = "Extra High", то RUSE1 = 1.24;
# если PDIF = "Low", то PDIF1 = 0,87, если PDIF = "Nominal", то PDIF1 = 1.00, если PDIF = "High", то PDIF1 = 1.29, если PDIF = "Very High", то PDIF1 = 1.81, если PDIF = "Extra High", то PDIF1 = 2.61;
# если PREX = "Extra Low", то PREX1 = 1.59, если PREX = "Very Low", то PREX1 = 1.33, если PREX = "Low", то PREX1 = 1,22, если PREX = "Nominal", то PREX1 = 1.00, если PREX = "High", то PREX1 = 0.87, если PREX = "Very High", то PREX1 = 0.74, если PREX = "Extra High", то PREX1 = 0.62;
# если FCIL = "Extra Low", то FCIL1 = 1.43, если FCIL = "Very Low", то FCIL1 = 1.30, если FCIL = "Low", то FCIL1 = 1,10, если FCIL = "Nominal", то FCIL1 = 1.00, если FCIL = "High", то FCIL1 = 0.87, если FCIL = "Very High", то FCIL1 = 0.73, если FCIL = "Extra High", то FCIL1 = 0.62;
# если SCED = "Very Low", то SCED1 = 1.43, если SCED = "Low", то SCED1 = 1,14, если SCED = "Nominal", то SCED1 = 1.00, если SCED = "High", то SCED1 = 1.00, если SCED = "Very High", то SCED1 = 1.00;
    # Определение значений для PERS1
    if PERS == "Extra Low":
        PERS1 = 2.12
    elif PERS == "Very Low":
        PERS1 = 1.62
    elif PERS == "Low":
        PERS1 = 1.26
    elif PERS == "Nominal":
        PERS1 = 1.00
    elif PERS == "High":
        PERS1 = 0.83
    elif PERS == "Very High":
        PERS1 = 0.63
    elif PERS == "Extra High":
        PERS1 = 0.50

    # Определение значений для RCPX1
    if RCPX == "Extra Low":
        RCPX1 = 0.49
    elif RCPX == "Very Low":
        RCPX1 = 0.60
    elif RCPX == "Low":
        RCPX1 = 0.83
    elif RCPX == "Nominal":
        RCPX1 = 1.00
    elif RCPX == "High":
        RCPX1 = 1.33
    elif RCPX == "Very High":
        RCPX1 = 1.91
    elif RCPX == "Extra High":
        RCPX1 = 2.72

    # Определение значений для RUSE1
    if RUSE == "Low":
        RUSE1 = 0.95
    elif RUSE == "Nominal":
        RUSE1 = 1.00
    elif RUSE == "High":
        RUSE1 = 1.07
    elif RUSE == "Very High":
        RUSE1 = 1.15
    elif RUSE == "Extra High":
        RUSE1 = 1.24

    # Определение значений для PDIF1
    if PDIF == "Low":
        PDIF1 = 0.87
    elif PDIF == "Nominal":
        PDIF1 = 1.00
    elif PDIF == "High":
        PDIF1 = 1.29
    elif PDIF == "Very High":
        PDIF1 = 1.81
    elif PDIF == "Extra High":
        PDIF1 = 2.61

    # Определение значений для PREX1
    if PREX == "Extra Low":
        PREX1 = 1.59
    elif PREX == "Very Low":
        PREX1 = 1.33
    elif PREX == "Low":
        PREX1 = 1.22
    elif PREX == "Nominal":
        PREX1 = 1.00
    elif PREX == "High":
        PREX1 = 0.87
    elif PREX == "Very High":
        PREX1 = 0.74
    elif PREX == "Extra High":
        PREX1 = 0.62

    # Определение значений для FCIL1
    if FCIL == "Extra Low":
        FCIL1 = 1.43
    elif FCIL == "Very Low":
        FCIL1 = 1.30
    elif FCIL == "Low":
        FCIL1 = 1.10
    elif FCIL == "Nominal":
        FCIL1 = 1.00
    elif FCIL == "High":
        FCIL1 = 0.87
    elif FCIL == "Very High":
        FCIL1 = 0.73
    elif FCIL == "Extra High":
        FCIL1 = 0.62

    # Определение значений для SCED1
    if SCED == "Very Low":
        SCED1 = 1.43
    elif SCED == "Low":
        SCED1 = 1.14
    elif SCED == "Nominal":
        SCED1 = 1.00
    elif SCED == "High":
        SCED1 = 1.00
    elif SCED == "Very High":
        SCED1 = 1.00

    EM_mult = PERS1 * RCPX1 * RUSE1 * PDIF1 * PREX1 * FCIL1 * SCED1
    return EM_mult


In [ ]:
# Ввод множителей трудоемкости. Варианты оценки: "Extra Low", "Very Low", "Low", "Nominal", "High", "Very High", "Extra High".
PERS = "Low"       # Квалификация персонала. Значения от "Extra Low" до "Extra High".
RCPX = "Very Low"  # Сложность и надежность продукта. Значения от "Extra Low" до "Extra High".
RUSE = "Nominal"   # Разработка для повторного использования. Значения от "Low" до "Extra High".
PDIF = "Nominal"   # Сложность платформы разработки. Значения от "Low" до "Extra High".
PREX = "Very High" # Опыт персонала. Значения от "Extra Low" до "Extra High".
FCIL = "High"      # Оборудование. Значения от "Extra Low" до "Extra High".
SCED = "Low"       # Сжатие расписания. Значения от "Very Low" до "Very High".
EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED)
print(f"При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение {round(EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED),2)}")

При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение 0.55


In [ ]:
SIZE = 7.2 # размер продукта в KSLOC, тысячах строк исходного кода.
PM = 2.94 * (SIZE**(E)) * EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED)
print(f"При рассчитанных выше параметрах, а также размере продукта в {SIZE} KSLOC, оценка трудоемкости проекта PC принимает значение {round(PM,2)} чел*мес")

При рассчитанных выше параметрах, а также размере продукта в 7.2 KSLOC, оценка трудоемкости проекта PC принимает значение 13.49 чел*мес


# Нечеткая модель *COCOMO II*. Применение трапециевидных нечетких чисел 2 типа

Нечеткие трапециевидные числа второго типа имеют две ФП - верхнюю и нижнюю для ИНМ2Т и функции принадлежности и непринадлежности для интуиционистских НМ, отражающие сомнения эксперта в оценках границ нечеткости, т.е. правая и левая границы нечеткости имеют по 2 значения. Левая граница - это минимальное значение нечеткости, правая, соответственно, максимальное.

In [ ]:
# Функция округления параметров трапециевидного нечеткого числа (интуиционистского или интервального 2 типа)
def round_fuzzy_number(fuzzy_number):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    return ((round(x1, 3), round(x2, 3), round(x3, 3), round(x4, 3)),
            (round(x5, 3), round(x6, 3), round(x7, 3), round(x8, 3)))

In [ ]:
# Функция умножения трапециевидного нечеткого числа (интуиционистского или интервального 2 типа) на константу
def multiply_fuzzy_number_by_constant(fuzzy_number, constant):
    # Умножение нечеткого числа на константу
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    if constant < 0:
        # Умножение всех координат на константу в обратном порядке
        new_X = (
            (x4 * constant, x3 * constant, x2 * constant, x1 * constant),
            (x8 * constant, x7 * constant, x6 * constant, x5 * constant)
        )
    else:
        # Умножение всех координат на константу в обычном порядке
        new_X = (
            (x1 * constant, x2 * constant, x3 * constant, x4 * constant),
            (x5 * constant, x6 * constant, x7 * constant, x8 * constant)
        )
    return new_X

In [ ]:
# Функция сложения двух трапециевидных нечетких чисел (интуиционистских или интервальных 2 типа)
def add_intuitionistic_trapezoidal_fuzzy_numbers(fuzzy_number1, fuzzy_number2):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number1
    (y1, y2, y3, y4), (y5, y6, y7, y8) = fuzzy_number2
    return ((round(x1 + y1, 3), round(x2 + y2, 3), round(x3 + y3, 3), round(x4 + y4, 3)),
            (round(x5 + y5, 3), round(x6 + y6, 3), round(x7 + y7, 3), round(x8 + y8, 3)))

In [ ]:
# Функция для вычисления альфа-среза
def alpha_cut(fuzzy_number, alpha):
    # Распаковка параметров нечеткого числа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number

    # Вычисление концов верхнего интервала альфа-среза
    upper_start = alpha * x2 + (1 - alpha) * x1
    upper_end = alpha * x3 + (1 - alpha) * x4

    # Вычисление концов нижнего интервала альфа-среза
    lower_start = alpha * x6 + (1 - alpha) * x5
    lower_end = alpha * x7 + (1 - alpha) * x8

    # Округляем значения до 3 знаков после запятой
    upper_start = round(upper_start, 3)
    upper_end = round(upper_end, 3)
    lower_start = round(lower_start, 3)
    lower_end = round(lower_end, 3)

    # Возвращаем альфа-срез в виде нечеткого числа
    return ((upper_start, upper_end), (lower_start, lower_end))

In [ ]:
# Функция вычисления центроида системы двух точек
def centroid(alpha_cut_result):
    # Распаковка верхнего и нижнего отрезков альфа-среза
    (upper_start, upper_end), (lower_start, lower_end) = alpha_cut_result

    # Расчет среднего значения
    central_upper = round((upper_start + upper_end) / 2, 3)
    central_lower = round((lower_start + lower_end) / 2, 3)

    # Возвращаем результат в нужном формате
    return (central_upper, central_lower)

In [ ]:
# Функция вычисления среднего арифметического дефаззифицированных значений двух функция принадлежности
def calculate_average(defuzzified_values):
    # Извлекаем значения из кортежа
    defuzzified_upper, defuzzified_lower = defuzzified_values
    # Вычисляем среднее арифметическое
    average = round((defuzzified_upper + defuzzified_lower) / 2, 3)
    return average

In [ ]:
def calculate_SF_summ(*params):
    SF_summ = params[0]
    for param in params[1:]:
        SF_summ = add_intuitionistic_trapezoidal_fuzzy_numbers(SF_summ, param)
    return SF_summ

def SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT):
    # Определение значений для PREC1
    if PREC == "Very Low":
        PREC1 = ((4.96, 5.70, 6.70, 7.44), (5.33, 5.70, 6.70, 7.07))
    elif PREC == "Low":
        PREC1 = ((3.72, 4.46, 5.46, 6.20), (4.09, 4.46, 5.46, 5.83))
    elif PREC == "Nominal":
        PREC1 = ((2.48, 3.22, 4.22, 4.96), (2.85, 3.22, 4.22, 4.59))
    elif PREC == "High":
        PREC1 = ((1.24, 1.98, 2.98, 3.72), (1.61, 1.98, 2.98, 3.35))
    elif PREC == "Very High":
        PREC1 = ((0.00, 0.74, 1.74, 2.48), (0.37, 0.74, 1.74, 2.11))
    elif PREC == "Extra High":
        PREC1 = ((0.00, 0.00, 0.00, 1.24), (0.00, 0.00, 0.00, 0.62))
    else:
        raise ValueError("PREC не соответствует заданным вариантам оценки")

    # Определение значений для FLEX1
    if FLEX == "Very Low":
        FLEX1 = ((4.05, 4.57, 5.57, 6.09), (4.31, 4.57, 5.57, 5.83))
    elif FLEX == "Low":
        FLEX1 = ((3.04, 3.55, 4.55, 5.07), (3.30, 3.55, 4.55, 4.81))
    elif FLEX == "Nominal":
        FLEX1 = ((2.03, 2.54, 3.54, 4.05), (2.29, 2.54, 3.54, 3.80))
    elif FLEX == "High":
        FLEX1 = ((1.01, 1.53, 2.53, 3.04), (1.27, 1.53, 2.53, 2.79))
    elif FLEX == "Very High":
        FLEX1 = ((0.00, 0.51, 1.51, 2.03), (0.26, 0.51, 1.51, 1.77))
    elif FLEX == "Extra High":
        FLEX1 = ((0.00, 0.00, 0.00, 1.01), (0.00, 0.00, 0.50, 0.51))
    else:
        raise ValueError("FLEX не соответствует заданным вариантам оценки")

    # Определение значений для RESL1
    if RESL == "Very Low":
        RESL1 = ((5.65, 6.57, 7.57, 8.49), (6.11, 6.57, 7.57, 8.03))
    elif RESL == "Low":
        RESL1 = ((4.24, 5.15, 6.15, 7.07), (4.70, 5.15, 6.15, 6.61))
    elif RESL == "Nominal":
        RESL1 = ((2.83, 3.74, 4.74, 5.65), (3.29, 3.74, 4.74, 5.20))
    elif RESL == "High":
        RESL1 = ((1.41, 2.33, 3.33, 4.24), (1.87, 2.33, 3.33, 3.79))
    elif RESL == "Very High":
        RESL1 = ((0.00, 0.91, 1.91, 2.83), (0.46, 0.91, 1.91, 2.37))
    elif RESL == "Extra High":
        RESL1 = ((0.00, 0.00, 0.00, 1.41), (0.00, 0.00, 0.00, 0.71))
    else:
        raise ValueError("RESL не соответствует заданным вариантам оценки")

    # Определение значений для TEAM1
    if TEAM == "Very Low":
        TEAM1 = ((4.38, 4.98, 5.98, 6.58), (4.68, 4.98, 5.98, 6.28))
    elif TEAM == "Low":
        TEAM1 = ((3.29, 3.88, 4.88, 5.48), (3.59, 3.88, 4.88, 5.18))
    elif TEAM == "Nominal":
        TEAM1 = ((2.19, 2.79, 3.79, 4.38), (2.49, 2.79, 3.79, 4.09))
    elif TEAM == "High":
        TEAM1 = ((1.10, 1.69, 2.69, 3.29), (1.40, 1.69, 2.69, 2.99))
    elif TEAM == "Very High":
        TEAM1 = ((0.00, 0.60, 1.60, 2.19), (0.30, 0.60, 1.60, 1.90))
    elif TEAM == "Extra High":
        TEAM1 = ((0.00, 0.00, 0.00, 1.10), (0.00, 0.00, 0.00, 0.55))
    else:
        raise ValueError("TEAM не соответствует заданным вариантам оценки")

    # Определение значений для PMAT1
    if PMAT == "Very Low":
        PMAT1 = ((6.24, 7.30, 8.30, 9.36), (6.77, 7.30, 8.30, 8.83))
    elif PMAT == "Low":
        PMAT1 = ((4.68, 5.74, 6.74, 7.80), (5.21, 5.74, 6.74, 7.27))
    elif PMAT == "Nominal":
        PMAT1 = ((3.12, 4.18, 5.18, 6.24), (3.65, 4.18, 5.18, 5.71))
    elif PMAT == "High":
        PMAT1 = ((1.56, 2.62, 3.62, 4.68), (2.09, 2.62, 3.62, 4.15))
    elif PMAT == "Very High":
        PMAT1 = ((0.00, 1.06, 2.06, 3.12), (0.53, 1.06, 2.06, 2.59))
    elif PMAT == "Extra High":
        PMAT1 = ((0.00, 0.00, 0.00, 1.56), (0.00, 0.00, 0.00, 0.78))
    else:
        raise ValueError("PMAT не соответствует заданным вариантам оценки")

    print(f"PREC = {PREC} принимает значение {PREC1}")
    print(f"FLEX = {FLEX} принимает значение {FLEX1}")
    print(f"RESL = {RESL} принимает значение {RESL1}")
    print(f"TEAM = {TEAM} принимает значение {TEAM1}")
    print(f"PMAT = {PMAT} принимает значение {PMAT1}")

    # Вычисляем итоговый SF
    SF = calculate_SF_summ(PREC1, FLEX1, RESL1, TEAM1, PMAT1)

    return SF

In [ ]:
# Ввод факторов масштаба. Варианты оценки: "Very Low", "Low", "Nominal", "High", "Very High", "Extra High"
PREC = "Nominal"    # Прецендентность, наличие опыта аналогичных разработок
FLEX = "Low"        # Гибкость процесса разработки
RESL = "High"       # Архитектура и разрешение рисков
TEAM = "Very Low"   # Сработанность команды
PMAT = "Extra High" # Зрелость процессов

SF_summ = SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT)
print(f"При вышеуказанных значениях факторов масштаба, суммарный эффект SF принимает значение {SF_summ}")

PREC = Nominal принимает значение ((2.48, 3.22, 4.22, 4.96), (2.85, 3.22, 4.22, 4.59))
FLEX = Low принимает значение ((3.04, 3.55, 4.55, 5.07), (3.3, 3.55, 4.55, 4.81))
RESL = High принимает значение ((1.41, 2.33, 3.33, 4.24), (1.87, 2.33, 3.33, 3.79))
TEAM = Very Low принимает значение ((4.38, 4.98, 5.98, 6.58), (4.68, 4.98, 5.98, 6.28))
PMAT = Extra High принимает значение ((0.0, 0.0, 0.0, 1.56), (0.0, 0.0, 0.0, 0.78))
При вышеуказанных значениях факторов масштаба, суммарный эффект SF принимает значение ((11.31, 14.08, 18.08, 22.41), (12.7, 14.08, 18.08, 20.25))


In [ ]:
# Вычисление E = 0.91 + 0.01 * SF_summ

def add_constant_to_fuzzy_number(X, constant):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    # Прибавление константы ко всем координатам
    new_X = (
        (x1 + constant, x2 + constant, x3 + constant, x4 + constant),
        (x5 + constant, x6 + constant, x7 + constant, x8 + constant)
    )
    return new_X

# Умножаем SF_summ на 0.01
SF_summ_multiplied = multiply_fuzzy_number_by_constant(SF_summ, 0.01)

# Добавляем 0.91 к результату
E = add_constant_to_fuzzy_number(SF_summ_multiplied, 0.91)

# Округляем E
E_rounded = round_fuzzy_number(E)

In [ ]:
print(f"При вышеуказанных значениях факторов масштаба, показатель E принимает значение {E_rounded}")

При вышеуказанных значениях факторов масштаба, показатель E принимает значение ((1.023, 1.051, 1.091, 1.134), (1.037, 1.051, 1.091, 1.113))


Для перехода от нечетких значений к четким применим операцию альфа-среза. В результате получим четкий интервал (отрезок) значений из области определения нечеткого трепециевидного числа 2-го типа, который будет соответствовать единственному значению функции принадлежности, заданному уровнем альфа-среза.

Зададим уровень альфа-среза равным 0.8. Значение альфа-среза - это уровень уверенности стейкхолдеров в полученной оценке итогового результата моделирования. Левая и права граница интервала (отрезка, являющегося результатом применения альфа-среза) - это минимальное (левая граница) и максимальное (правая граница) значения, которые может принимать результат моделирования с данной степенью уверенности.

In [ ]:
# Вычисление альфа-среза
alpha = 0.8
alpha_cut_result = alpha_cut(E_rounded, alpha)
print(f"Альфа-срез при альфа={alpha} для E_rounded {E_rounded} равен {alpha_cut_result}")

Альфа-срез при альфа=0.8 для E_rounded ((1.023, 1.051, 1.091, 1.134), (1.037, 1.051, 1.091, 1.113)) равен ((1.045, 1.1), (1.048, 1.095))


Другими словами, с 80% уверенностью можно утверждать, что величина показателя степени E составит от 1.045 до 1.1 ед. в верхней функции принадлежности и от 1.048 до 1.095 ед. в нижней функции принадлежности.

Для приведения интервальных оценок к точечным результатам применяются методы усреднения, например, центроид системы двух точек, которым является является середина отрезка, соединяющего данные точки, т.е. среднее арифметическое левого и правого значения его координат (среднее минимума и максимума по оси абсцисс).

In [ ]:
# Расчет центроида системы двух точек
alpha_cut_result = alpha_cut(E_rounded, alpha)
central_result = centroid(alpha_cut_result)

print(f"Усредненные значения для E_rounded {E_rounded} при альфа={alpha} равны {central_result}")

Усредненные значения для E_rounded ((1.023, 1.051, 1.091, 1.134), (1.037, 1.051, 1.091, 1.113)) при альфа=0.8 равны (1.073, 1.071)


In [ ]:
# Вычисляем среднее арифметическое усредненных значений
E_final = calculate_average(central_result)

print(f"Среднее арифметическое усредненных значений показателя степени E составляет {E_final}")


Среднее арифметическое усредненных значений показателя степени E составляет 1.072


Итак, усредненный (четкий) итоговый результат оценки показателя степени E составит составляет 1,072 ед.

In [ ]:
def multiply_intuitionistic_trapezoidal_fuzzy_numbers(X, Y):
    # Распаковка параметров интервальных трапециевидных чисел 2 типа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    (y1, y2, y3, y4), (y5, y6, y7, y8) = Y

    # Вычисление координат для произведения
    z1 = x2 * y1 - x2 * y2 + x1 * y2
    z2 = x2 * y2
    z3 = x3 * y3
    z4 = x3 * y4 - x3 * y3 + y3 * x4

    z5 = x6 * y5 - x6 * y6 + x5 * y6
    z6 = x6 * y6
    z7 = x7 * y7
    z8 = x7 * y8 - x7 * y7 + y7 * x8

    return ((z1, z2, z3, z4), (z5, z6, z7, z8))

def calculate_SF_multiply(*params):
    EM_multiply = params[0]
    for param in params[1:]:
        EM_multiply = multiply_intuitionistic_trapezoidal_fuzzy_numbers (EM_multiply, param)
    return EM_multiply

def EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED):
    # Определение значений для PERS1
    if PERS == "Extra Low":
        PERS1 = ((1.62, 2.07, 2.17, 2.62), (1.85, 2.07, 2.17, 2.40))
    elif PERS == "Very Low":
        PERS1 = ((1.26, 1.57, 1.67, 2.12), (1.42, 1.57, 1.67, 1.90))
    elif PERS == "Low":
        PERS1 = ((1.00, 1.21, 1.31, 1.62), (1.11, 1.21, 1.31, 1.47))
    elif PERS == "Nominal":
        PERS1 = ((0.83, 0.95, 1.05, 1.26), (0.89, 0.95, 1.05, 1.16))
    elif PERS == "High":
        PERS1 = ((0.63, 0.78, 0.88, 1.00), (0.71, 0.78, 0.88, 0.94))
    elif PERS == "Very High":
        PERS1 = ((0.50, 0.58, 0.68, 0.83), (0.54, 0.58, 0.68, 0.76))
    elif PERS == "Extra High":
        PERS1 = ((0.37, 0.45, 0.55, 0.63), (0.41, 0.45, 0.55, 0.59))

    # Определение значений для RCPX1
    if RCPX == "Extra Low":
        RCPX1 = ((0.38, 0.44, 0.54, 0.60), (0.41, 0.44, 0.54, 0.57))
    elif RCPX == "Very Low":
        RCPX1 = ((0.49, 0.55, 0.65, 0.83), (0.52, 0.55, 0.65, 0.74))
    elif RCPX == "Low":
        RCPX1 = ((0.60, 0.78, 0.88, 1.00), (0.69, 0.78, 0.88, 0.94))
    elif RCPX == "Nominal":
        RCPX1 = ((0.83, 0.95, 1.05, 1.33), (0.89, 0.95, 1.05, 1.19))
    elif RCPX == "High":
        RCPX1 = ((1.00, 1.28, 1.38, 1.91), (1.14, 1.28, 1.38, 1.65))
    elif RCPX == "Very High":
        RCPX1 = ((1.33, 1.86, 1.96, 2.72), (1.60, 1.86, 1.96, 2.34))
    elif RCPX == "Extra High":
        RCPX1 = ((1.91, 2.67, 2.77, 3.15), (2.29, 2.67, 2.77, 2.96))

    # Определение значений для RUSE1
    if RUSE == "Low":
        RUSE1 = ((0.90, 0.94, 0.96, 1.00), (0.92, 0.94, 0.96, 1.98))
    elif RUSE == "Nominal":
        RUSE1 = ((0.95, 0.99, 1.01, 1.07), (0.97, 0.99, 1.01, 1.04))
    elif RUSE == "High":
        RUSE1 = ((1.00, 1.06, 1.08, 1.15), (1.03, 1.06, 1.08, 1.12))
    elif RUSE == "Very High":
        RUSE1 = ((1.07, 1.14, 1.16, 1.24), (1.11, 1.14, 1.16, 1.20))
    elif RUSE == "Extra High":
        RUSE1 = ((1.15, 1.23, 1.25, 1.29), (1.19, 1.23, 1.25, 1.27))

    # Определение значений для PDIF1
    if PDIF == "Low":
        PDIF1 = ((0.74, 0.82, 0.92, 1.00), (0.78, 0.82, 0.92, 0.96))
    elif PDIF == "Nominal":
        PDIF1 = ((0.87, 0.95, 1.05, 1.29), (0.91, 0.95, 1.05, 1.17))
    elif PDIF == "High":
        PDIF1 = ((1.00, 1.24, 1.34, 1.81), (1.12, 1.24, 1.34, 1.58))
    elif PDIF == "Very High":
        PDIF1 = ((1.29, 1.76, 1.86, 2.61), (1.53, 1.76, 1.86, 2.24))
    elif PDIF == "Extra High":
        PDIF1 = ((1.81, 2.56, 2.66, 3.04), (2.19, 2.56, 2.66, 2.85))

    # Определение значений для PREX1
    if PREX == "Extra Low":
        PREX1 = ((1.33, 1.54, 1.64, 1.85), (1.44, 1.54, 1.64, 1.75))
    elif PREX == "Very Low":
        PREX1 = ((1.22, 1.28, 1.38, 1.59), (1.25, 1.28, 1.38, 1.49))
    elif PREX == "Low":
        PREX1 = ((1.00, 1.17, 1.27, 1.33), (1.09, 1.17, 1.27, 1.30))
    elif PREX == "Nominal":
        PREX1 = ((0.87, 0.95, 1.05, 1.22), (0.91, 0.95, 1.05, 1.14))
    elif PREX == "High":
        PREX1 = ((0.74, 0.82, 0.92, 1.00), (0.78, 0.82, 0.92, 0.96))
    elif PREX == "Very High":
        PREX1 = ((0.62, 0.69, 0.79, 0.87), (0.66, 0.69, 0.79, 0.83))
    elif PREX == "Extra High":
        PREX1 = ((0.50, 0.57, 0.67, 0.74), (0.54, 0.57, 0.67, 0.71))

    # Определение значений для FCIL1
    if FCIL == "Extra Low":
        FCIL1 = ((1.30, 1.38, 1.48, 1.56), (1.34, 1.38, 1.48, 1.52))
    elif FCIL == "Very Low":
        FCIL1 = ((1.10, 1.25, 1.35, 1.43), (1.18, 1.25, 1.35, 1.39))
    elif FCIL == "Low":
        FCIL1 = ((1.00, 1.05, 1.15, 1.30), (1.03, 1.05, 1.15, 1.23))
    elif FCIL == "Nominal":
        FCIL1 = ((0.87, 0.95, 1.05, 1.10), (0.91, 0.95, 1.05, 1.08))
    elif FCIL == "High":
        FCIL1 = ((0.73, 0.82, 0.92, 1.00), (0.78, 0.82, 0.92, 0.96))
    elif FCIL == "Very High":
        FCIL1 = ((0.62, 0.68, 0.78, 0.87), (0.65, 0.68, 0.78, 0.83))
    elif FCIL == "Extra High":
        FCIL1 = ((0.51, 0.57, 0.67, 0.73), (0.54, 0.57, 0.67, 0.70))

    # Определение значений для SCED1
    if SCED == "Very Low":
        SCED1 = ((1.14, 1.38, 1.48, 1.72), (1.26, 1.38, 1.48, 1.60))
    elif SCED == "Low":
        SCED1 = ((1.00, 1.09, 1.19, 1.43), (1.05, 1.09, 1.19, 1.31))
    elif SCED == "Nominal":
        SCED1 = ((0.86, 0.95, 1.05, 1.14), (0.91, 0.95, 1.05, 1.10))
    elif SCED == "High":
        SCED1 = ((0.86, 0.95, 1.05, 1.14), (0.91, 0.95, 1.05, 1.10))
    elif SCED == "Very High":
        SCED1 = ((0.86, 0.95, 1.05, 1.14), (0.91, 0.95, 1.05, 1.10))

    print(f"PERS = {PERS} принимает значение {PERS1}")
    print(f"RCPX = {RCPX} принимает значение {RCPX1}")
    print(f"RUSE = {RUSE} принимает значение {RUSE1}")
    print(f"PDIF = {PDIF} принимает значение {PDIF1}")
    print(f"PREX = {PREX} принимает значение {PREX1}")
    print(f"FCIL = {FCIL} принимает значение {FCIL1}")
    print(f"SCED = {SCED} принимает значение {SCED1}")

    EM_mult= calculate_SF_multiply(PERS1, RCPX1, RUSE1, PDIF1, PREX1, FCIL1, SCED1)
    return EM_mult

In [ ]:
# Ввод множителей трудоемкости. Варианты оценки: "Extra Low", "Very Low", "Low", "Nominal", "High", "Very High", "Extra High".
PERS = "Low"       # валификация персонала. Значения от "Extra Low" до "Extra High".
RCPX = "Very Low"  # Сложность и надежность продукта. Значения от "Extra Low" до "Extra High".
RUSE = "Nominal"   # Разработка для повторного использования. Значения от "Low" до "Extra High".
PDIF = "Nominal"   # Сложность платформы разработки. Значения от "Low" до "Extra High".
PREX = "Very High" # Опыт персонала. Значения от "Extra Low" до "Extra High".
FCIL = "High"      # Оборудование. Значения от "Extra Low" до "Extra High".
SCED = "Low"       # Сжатие расписания. Значения от "Very Low" до "Very High".

EM_multiply = EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED)
# Округляем E
EM_rounded = round_fuzzy_number(EM_multiply)

print(f"При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение {EM_rounded}")

PERS = Low принимает значение ((1.0, 1.21, 1.31, 1.62), (1.11, 1.21, 1.31, 1.47))
RCPX = Very Low принимает значение ((0.49, 0.55, 0.65, 0.83), (0.52, 0.55, 0.65, 0.74))
RUSE = Nominal принимает значение ((0.95, 0.99, 1.01, 1.07), (0.97, 0.99, 1.01, 1.04))
PDIF = Nominal принимает значение ((0.87, 0.95, 1.05, 1.29), (0.91, 0.95, 1.05, 1.17))
PREX = Very High принимает значение ((0.62, 0.69, 0.79, 0.87), (0.66, 0.69, 0.79, 0.83))
FCIL = High принимает значение ((0.73, 0.82, 0.92, 1.0), (0.78, 0.82, 0.92, 0.96))
SCED = Low принимает значение ((1.0, 1.09, 1.19, 1.43), (1.05, 1.09, 1.19, 1.31))
При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение ((0.115, 0.386, 0.781, 1.712), (0.259, 0.386, 0.781, 1.249))


Для возведения параметра *SIZE*, заданного трапециевидным нечетким числом 2-го типа, применим методы приближенного вычисления, приняв, что $(a1, a2, a3, a4)*(b1, b2, b3, b4) \approx (a1*b1, a2*b2, a3*b3, a4*b4)$

 Тогда возведение трапециевидного числа в степень примет вид: $(a1, a2, a3, a4)^E \approx (a1^E, a2^E, a3^E, a4^E)$. В данном случае возведение будет точно в степень E, но показатели левой и правой границ нечеткости $a1^E$ и $a4^E$ будут вычислены приблизительно.


In [ ]:
# Вычисление PM = 2.94 * (SIZE**(E)) * (EM_rounded)

def fuzzy_number_exponentiation (fuzzy_number, constant):
    # Возведение нечеткого числа в степень
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    return ((x1**constant, x2**constant, x3**constant, x4**constant),
            (x5**constant, x6**constant, x7**constant, x8**constant))

def multiply_intuitionistic_trapezoidal_fuzzy_numbers(X, Y):
    # Произведение двух нечетких трапециевидных чисел
    # Распаковка параметров интервальных трапециевидных чисел 2 типа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    (y1, y2, y3, y4), (y5, y6, y7, y8) = Y

    # Вычисление координат для произведения с округлением
    z1 = round(x2 * y1 - x2 * y2 + x1 * y2, 2)
    z2 = round(x2 * y2, 2)
    z3 = round(x3 * y3, 2)
    z4 = round(x3 * y4 - x3 * y3 + y3 * x4, 2)

    z5 = round(x6 * y5 - x6 * y6 + x5 * y6, 2)
    z6 = round(x6 * y6, 2)
    z7 = round(x7 * y7, 2)
    z8 = round(x7 * y8 - x7 * y7 + y7 * x8, 2)

    return ((z1, z2, z3, z4), (z5, z6, z7, z8))


SIZE = (5.7, 6.7, 7.7, 8.7), (6.2, 6.7, 7.7, 8.2)  # Размер продукта в KSLOC, тысячах строк исходного кода.

# Возведение SIZE в степень E
SIZE_exp_E = fuzzy_number_exponentiation (SIZE, E_final)

# Умножаем SIZE_exp_E на 2.94
SIZE_exp_E_mult_A = multiply_fuzzy_number_by_constant(SIZE_exp_E, 2.94)

# Умножение интервальных трапециевидных чисел 2 типа
PM = multiply_intuitionistic_trapezoidal_fuzzy_numbers(SIZE_exp_E_mult_A, EM_rounded)

# Округляем PM
PM_rounded = round_fuzzy_number(PM)

print(f"При рассчитанных выше параметрах, а также размере продукта в {SIZE} KSLOC, оценка трудоемкости проекта PM принимает значение {PM_rounded} чел*мес")

При рассчитанных выше параметрах, а также размере продукта в ((5.7, 6.7, 7.7, 8.7), (6.2, 6.7, 7.7, 8.2)) KSLOC, оценка трудоемкости проекта PM принимает значение ((1.21, 8.72, 20.48, 47.76), (5.15, 8.72, 20.48, 34.18)) чел*мес


Для перехода от нечетких значений к четким применим операцию альфа-среза. В результате получим четкий интервал (отрезок) значений из области определения нечеткого трепециевидного числа 2-го типа, который будет соответствовать единственному значению функции принадлежности, заданному уровнем альфа-среза.

Зададим уровень альфа-среза равным 0.8. Значение альфа-среза - это уровень уверенности стейкхолдеров в полученной оценке итогового результата моделирования. Левая и права граница интервала (отрезка, являющегося результатом применения альфа-среза) - это минимальное (левая граница) и максимальное (правая граница) значения, которые может принимать результат моделирования с данной степенью уверенности.

In [ ]:
# Вычисление альфа-среза
alpha = 0.8
alpha_cut_result = alpha_cut(PM_rounded, alpha)
print(f"Альфа-срез при альфа={alpha} для PM_rounded {PM_rounded} равен {alpha_cut_result}")

Альфа-срез при альфа=0.8 для PM_rounded ((1.21, 8.72, 20.48, 47.76), (5.15, 8.72, 20.48, 34.18)) равен ((7.218, 25.936), (8.006, 23.22))


Другими словами, с 80% уверенностью можно утверждать, что итоговый результат оценки трудоемкости проекта составит от 7.22 до 25.94 чел∙мес в верхней функции принадлежности и от 8.01 до 23.22 чел∙мес в нижней функции принадлежности.

Для приведения интервальных оценок к точечным результатам применяются методы усреднения, например, центроид системы двух точек, которым является является середина отрезка, соединяющего данные точки, т.е. среднее арифметическое левого и правого значения его координат (среднее минимума и максимума по оси абсцисс).

In [ ]:
alpha_cut_result = alpha_cut(PM_rounded, alpha)
central_result = centroid(alpha_cut_result)

print(f"Усредненные значения для PM_rounded {PM_rounded} при альфа = {alpha} равны {central_result}")

Усредненные значения для PM_rounded ((1.21, 8.72, 20.48, 47.76), (5.15, 8.72, 20.48, 34.18)) при альфа = 0.8 равны (16.577, 15.613)


In [ ]:
# Вычисляем среднее арифметическое усредненных значений
PM_final = calculate_average(central_result)

print(f"Среднее значение трудоемкости по нечеткой модели составляет {PM_final} чел.*мес.")

Среднее значение трудоемкости по нечеткой модели составляет 16.095 чел.*мес.


# Нечеткая модель *COCOMO II*. Применение колеблющихся нечетких чисел.

In [ ]:
# Функция для обработки результата - исключение повторов и упорядочивание по возрастанию значений функции принадлежности
def process_fuzzy_result(fuzzy_result):
    # Распаковка результата
    x_value, *parameters = fuzzy_result

    # Исключение повторяющихся значений и упорядочение по возрастанию
    unique_parameters = sorted(set(parameters))

    # Формирование нового кортежа с уникальными значениями
    processed_result = (x_value, *unique_parameters)

    return processed_result

In [ ]:
# Функция для умножения дискретного колеблющегося нечеткого числа на константу
def multiply_fuzzy_number_with_constant(X, A):
    x, *parameters = X
    Z = round(A * x, 3)
    new_parameters = [round(1 - (1 - param) ** A, 2) for param in parameters]
    return (round(Z, 3), *new_parameters)

In [ ]:
# Вычисление суммы значений факторов масштаба SF
def add_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X
    y_value, *y_parameters = Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for xi in x_parameters:
        for yj in y_parameters:
            # Вычисление параметров для Z
            zij = round((xi + yj - xi*yj), 2)
            result_parameters.append(zij)

    # Вычисление значения Z
    Z = round(x_value + y_value, 2)

    return (Z, *result_parameters)

def calculate_SF_summ(*params):
    SF_summ = params[0]
    for param in params[1:]:
        SF_summ = add_discrete_fuzzy_numbers(SF_summ, param)
    return SF_summ

def SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT):
    # Определение значений для PREC1
    if PREC == "Very Low":
        PREC1 = (6.20, 0.5, 0.6)
    elif PREC == "Low":
        PREC1 = (4.96, 0.5, 0.6)
    elif PREC == "Nominal":
        PREC1 = (3.72, 0.5, 0.6)
    elif PREC == "High":
        PREC1 = (2.48, 0.5, 0.6)
    elif PREC == "Very High":
        PREC1 = (1.24, 0.5, 0.6)
    elif PREC == "Extra High":
        PREC1 = (0.00, 0.5, 0.6)
    else:
        raise ValueError("PREC не соответствует заданным вариантам оценки")

    # Определение значений для FLEX1
    if FLEX == "Very Low":
        FLEX1 = (5.07, 0.5, 0.6)
    elif FLEX == "Low":
        FLEX1 = (4.05, 0.5, 0.6)
    elif FLEX == "Nominal":
        FLEX1 = (3.04, 0.5, 0.6)
    elif FLEX == "High":
        FLEX1 = (2.03, 0.5, 0.6)
    elif FLEX == "Very High":
        FLEX1 = (1.01, 0.5, 0.6)
    elif FLEX == "Extra High":
        FLEX1 = (0.00, 0.5, 0.6)
    else:
        raise ValueError("FLEX не соответствует заданным вариантам оценки")

    # Определение значений для RESL1
    if RESL == "Very Low":
        RESL1 = (7.07, 0.5, 0.6)
    elif RESL == "Low":
        RESL1 = (5.65, 0.5, 0.6)
    elif RESL == "Nominal":
        RESL1 = (4.24, 0.5, 0.6)
    elif RESL == "High":
        RESL1 = (2.83, 0.5, 0.6)
    elif RESL == "Very High":
        RESL1 = (1.41, 0.5, 0.6)
    elif RESL == "Extra High":
        RESL1 = (0.00, 0.5, 0.6)
    else:
        raise ValueError("RESL не соответствует заданным вариантам оценки")

    # Определение значений для TEAM1
    if TEAM == "Very Low":
        TEAM1 = (5.48, 0.5, 0.6)
    elif TEAM == "Low":
        TEAM1 = (4.38, 0.5, 0.6)
    elif TEAM == "Nominal":
        TEAM1 = (3.29, 0.5, 0.6)
    elif TEAM == "High":
        TEAM1 = (2.19, 0.5, 0.6)
    elif TEAM == "Very High":
        TEAM1 = (1.10, 0.5, 0.6)
    elif TEAM == "Extra High":
        TEAM1 = (0.00, 0.5, 0.6)
    else:
        raise ValueError("TEAM не соответствует заданным вариантам оценки")

    # Определение значений для PMAT1
    if PMAT == "Very Low":
        PMAT1 = (7.80, 0.5, 0.6)
    elif PMAT == "Low":
        PMAT1 = (6.24, 0.5, 0.6)
    elif PMAT == "Nominal":
        PMAT1 = (4.68, 0.5, 0.6)
    elif PMAT == "High":
        PMAT1 = (3.12, 0.5, 0.6)
    elif PMAT == "Very High":
        PMAT1 = (1.56, 0.5, 0.6)
    elif PMAT == "Extra High":
        PMAT1 = (0.00, 0.5, 0.6)
    else:
        raise ValueError("PMAT не соответствует заданным вариантам оценки")

    print(f"PREC = {PREC} принимает значение {PREC1}")
    print(f"FLEX = {FLEX} принимает значение {FLEX1}")
    print(f"RESL = {RESL} принимает значение {RESL1}")
    print(f"TEAM = {TEAM} принимает значение {TEAM1}")
    print(f"PMAT = {PMAT} принимает значение {PMAT1}")

    # Вычисляем итоговый SF
    SF = calculate_SF_summ(PREC1, FLEX1, RESL1, TEAM1, PMAT1)

    return SF

In [ ]:
# Ввод факторов масштаба. Варианты оценки: "Very Low", "Low", "Nominal", "High", "Very High", "Extra High"
PREC = "Nominal"    # Прецендентность, наличие опыта аналогичных разработок
FLEX = "Low"        # Гибкость процесса разработки
RESL = "High"       # Архитектура и разрешение рисков
TEAM = "Very Low"   # Сработанность команды
PMAT = "Extra High" # Зрелость процессов

SF_summ = SF_COCOMOII(PREC, FLEX, RESL, TEAM, PMAT)
print(f"При вышеуказанных значениях факторов масштаба, суммарный эффект SF принимает значение {SF_summ}")

PREC = Nominal принимает значение (3.72, 0.5, 0.6)
FLEX = Low принимает значение (4.05, 0.5, 0.6)
RESL = High принимает значение (2.83, 0.5, 0.6)
TEAM = Very Low принимает значение (5.48, 0.5, 0.6)
PMAT = Extra High принимает значение (0.0, 0.5, 0.6)
При вышеуказанных значениях факторов масштаба, суммарный эффект SF принимает значение (16.08, 0.97, 0.98, 0.97, 0.98, 0.97, 0.98, 0.98, 0.98, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.99, 0.97, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.99, 0.98, 0.98, 0.98, 0.99, 0.98, 0.99, 0.99, 0.99)


In [ ]:
# Дополнение к коду для обработки результата
SF_summ_processed_result = process_fuzzy_result(SF_summ)

# Вывод обработанного результата
print(f"Обработанный результат SF_summ: {SF_summ_processed_result}")

Обработанный результат SF_summ: (16.08, 0.97, 0.98, 0.99)


In [ ]:
# Расчет показателя степени E = 0.91 + 0.01 * SF_summ

# Функция для суммирования дискретного колеблющегося числа с константой
def add_fuzzy_number_with_constant(X, A):
    # Распаковка параметров нечеткого числа
    x, *membership_degrees = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = x + A  # Сумма значения X и константы A

    # Параметры (степени принадлежности) остаются без изменений
    return (round(Z, 3), *membership_degrees)


# Умножаем SF_summ на 0.01
multiplied_result = multiply_fuzzy_number_with_constant(SF_summ, 0.01)

# Теперь прибавляем 0.91 к результату
E = add_fuzzy_number_with_constant(multiplied_result, 0.91)

# Вывод результата E
print(f"Значение нечеткого E: {E}")

Значение нечеткого E: (1.071, 0.03, 0.04, 0.03, 0.04, 0.03, 0.04, 0.04, 0.04, 0.03, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.03, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.05, 0.04, 0.04, 0.04, 0.05, 0.04, 0.05, 0.05, 0.05)


In [ ]:
E_processed_result = process_fuzzy_result(E)

# Вывод обработанного результата
print(f"Обработанный результат E_processed_result: {E_processed_result}")

Обработанный результат E_processed_result: (1.071, 0.03, 0.04, 0.05)


In [ ]:
# Вычисление четкого показателя степени E
def E_fuzzy_to_constant(X):
    # Распаковка параметров нечеткого числа
    x, *membership_degrees = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = x # Константа - это значение самого нечеткого числа без степеней принадлежности

    return (Z)

E_constant = E_fuzzy_to_constant(E)

print(f"Значение четкого E: {E_constant}")

Значение четкого E: 1.071


In [ ]:
def multiply_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X  # Извлекаем значение и параметры X
    y_value, *y_parameters = Y  # Извлекаем значение и параметры Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for x_param in x_parameters:
        for y_param in y_parameters:
            # Вычисление параметров для Z
            z_param = round(x_param * y_param, 2)
            result_parameters.append(z_param)

    # Вычисление значения Z
    Z_value = x_value * y_value  # Произведение значений X и Y

    return (round(Z_value, 3), *result_parameters)

def calculate_SF_multiply(*params):
    EM_multiply = params[0]
    for param in params[1:]:
        EM_multiply = multiply_discrete_fuzzy_numbers (EM_multiply, param)
    return EM_multiply

def EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED):
    # Определение значений для PERS1
    if PERS == "Extra Low":
        PERS1 = (2.12, 0.8, 0.9)
    elif PERS == "Very Low":
        PERS1 = (1.62, 0.8, 0.9)
    elif PERS == "Low":
        PERS1 = (1.26, 0.8, 0.9)
    elif PERS == "Nominal":
        PERS1 = (1.00, 0.8, 0.9)
    elif PERS == "High":
        PERS1 = (0.83, 0.8, 0.9)
    elif PERS == "Very High":
        PERS1 = (0.63, 0.8, 0.9)
    elif PERS == "Extra High":
        PERS1 = (0.50, 0.8, 0.9)

    # Определение значений для RCPX1
    if RCPX == "Extra Low":
        RCPX1 = (0.49, 0.8, 0.9)
    elif RCPX == "Very Low":
        RCPX1 = (0.60, 0.8, 0.9)
    elif RCPX == "Low":
        RCPX1 = (0.83, 0.8, 0.9)
    elif RCPX == "Nominal":
        RCPX1 = (1.00, 0.8, 0.9)
    elif RCPX == "High":
        RCPX1 = (1.33, 0.8, 0.9)
    elif RCPX == "Very High":
        RCPX1 = (1.91, 0.8, 0.9)
    elif RCPX == "Extra High":
        RCPX1 = (2.72, 0.8, 0.9)

    # Определение значений для RUSE1
    if RUSE == "Low":
        RUSE1 = (0.95, 0.8, 0.9)
    elif RUSE == "Nominal":
        RUSE1 = (1.00, 0.8, 0.9)
    elif RUSE == "High":
        RUSE1 = (1.07, 0.8, 0.9)
    elif RUSE == "Very High":
        RUSE1 = (1.15, 0.8, 0.9)
    elif RUSE == "Extra High":
        RUSE1 = (1.24, 0.8, 0.9)

    # Определение значений для PDIF1
    if PDIF == "Low":
        PDIF1 = (0.87, 0.8, 0.9)
    elif PDIF == "Nominal":
        PDIF1 = (1.00, 0.8, 0.9)
    elif PDIF == "High":
        PDIF1 = (1.29, 0.8, 0.9)
    elif PDIF == "Very High":
        PDIF1 = (1.81, 0.8, 0.9)
    elif PDIF == "Extra High":
        PDIF1 = (2.61, 0.8, 0.9)

    # Определение значений для PREX1
    if PREX == "Extra Low":
        PREX1 = (1.59, 0.8, 0.9)
    elif PREX == "Very Low":
        PREX1 = (1.33, 0.8, 0.9)
    elif PREX == "Low":
        PREX1 = (1.22, 0.8, 0.9)
    elif PREX == "Nominal":
        PREX1 = (1.00, 0.8, 0.9)
    elif PREX == "High":
        PREX1 = (0.87, 0.8, 0.9)
    elif PREX == "Very High":
        PREX1 = (0.74, 0.8, 0.9)
    elif PREX == "Extra High":
        PREX1 = (0.62, 0.8, 0.9)

    # Определение значений для FCIL1
    if FCIL == "Extra Low":
        FCIL1 = (1.43, 0.8, 0.9)
    elif FCIL == "Very Low":
        FCIL1 = (1.30, 0.8, 0.9)
    elif FCIL == "Low":
        FCIL1 = (1.10, 0.8, 0.9)
    elif FCIL == "Nominal":
        FCIL1 = (1.00, 0.8, 0.9)
    elif FCIL == "High":
        FCIL1 = (0.87, 0.8, 0.9)
    elif FCIL == "Very High":
        FCIL1 = (0.73, 0.8, 0.9)
    elif FCIL == "Extra High":
        FCIL1 = (0.62, 0.8, 0.9)

    # Определение значений для SCED1
    if SCED == "Very Low":
        SCED1 = (1.43, 0.8, 0.9)
    elif SCED == "Low":
        SCED1 = (1.14, 0.8, 0.9)
    elif SCED == "Nominal":
        SCED1 = (1.00, 0.8, 0.9)
    elif SCED == "High":
        SCED1 = (1.00, 0.8, 0.9)
    elif SCED == "Very High":
        SCED1 = (1.00, 0.8, 0.9)

    print(f"PERS = {PERS} принимает значение {PERS1}")
    print(f"RCPX = {RCPX} принимает значение {RCPX1}")
    print(f"RUSE = {RUSE} принимает значение {RUSE1}")
    print(f"PDIF = {PDIF} принимает значение {PDIF1}")
    print(f"PREX = {PREX} принимает значение {PREX1}")
    print(f"FCIL = {FCIL} принимает значение {FCIL1}")
    print(f"SCED = {SCED} принимает значение {SCED1}")

    EM_mult= calculate_SF_multiply(PERS1, RCPX1, RUSE1, PDIF1, PREX1, FCIL1, SCED1)
    return EM_mult

In [ ]:
# Ввод множителей трудоемкости. Варианты оценки: "Extra Low", "Very Low", "Low", "Nominal", "High", "Very High", "Extra High".
PERS = "Low"       # Квалификация персонала. Значения от "Extra Low" до "Extra High".
RCPX = "Very Low"  # Сложность и надежность продукта. Значения от "Extra Low" до "Extra High".
RUSE = "Nominal"   # Разработка для повторного использования. Значения от "Low" до "Extra High".
PDIF = "Nominal"   # Сложность платформы разработки. Значения от "Low" до "Extra High".
PREX = "Very High" # Опыт персонала. Значения от "Extra Low" до "Extra High".
FCIL = "High"      # Оборудование. Значения от "Extra Low" до "Extra High".
SCED = "Low"       # Сжатие расписания. Значения от "Very Low" до "Very High".

EM_multiply = EM_COCOMOII(PERS, RCPX, RUSE, PDIF, PREX, FCIL, SCED)

print(f"При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение {EM_multiply}")

PERS = Low принимает значение (1.26, 0.8, 0.9)
RCPX = Very Low принимает значение (0.6, 0.8, 0.9)
RUSE = Nominal принимает значение (1.0, 0.8, 0.9)
PDIF = Nominal принимает значение (1.0, 0.8, 0.9)
PREX = Very High принимает значение (0.74, 0.8, 0.9)
FCIL = High принимает значение (0.87, 0.8, 0.9)
SCED = Low принимает значение (1.14, 0.8, 0.9)
При вышеуказанных значениях множителей трудоемкости, произведение EMj принимает значение (0.554, 0.21, 0.23, 0.24, 0.27, 0.24, 0.27, 0.26, 0.3, 0.24, 0.27, 0.26, 0.3, 0.26, 0.3, 0.3, 0.33, 0.24, 0.27, 0.26, 0.3, 0.26, 0.3, 0.3, 0.33, 0.27, 0.31, 0.3, 0.34, 0.3, 0.34, 0.34, 0.38, 0.24, 0.27, 0.26, 0.3, 0.26, 0.3, 0.3, 0.33, 0.27, 0.31, 0.3, 0.34, 0.3, 0.34, 0.34, 0.38, 0.27, 0.31, 0.3, 0.34, 0.3, 0.34, 0.34, 0.38, 0.3, 0.34, 0.34, 0.38, 0.34, 0.38, 0.38, 0.43, 0.24, 0.27, 0.26, 0.3, 0.26, 0.3, 0.3, 0.33, 0.27, 0.31, 0.3, 0.34, 0.3, 0.34, 0.34, 0.38, 0.27, 0.31, 0.3, 0.34, 0.3, 0.34, 0.34, 0.38, 0.3, 0.34, 0.34, 0.38, 0.34, 0.38, 0.38, 0.43, 0.27, 

In [ ]:
# Дополнение к коду для обработки результата
EM_multiply_processed_result = process_fuzzy_result(EM_multiply)

# Вывод обработанного результата
print(f"Обработанный результат EM_multiply: {EM_multiply_processed_result}")

Обработанный результат EM_multiply: (0.554, 0.21, 0.23, 0.24, 0.26, 0.27, 0.3, 0.31, 0.33, 0.34, 0.37, 0.38, 0.42, 0.43, 0.48)


In [ ]:
def power_fuzzy_number_with_constant(X, A):
    # Распаковка параметров нечеткого числа
    x, *parameters = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = round(x ** A, 2)  # Возведение в степень A и округление до 2 знаков

    # Вычисление новых параметров для Z
    new_parameters = [round(param ** A, 2) for param in parameters]

    # Параметры (степени принадлежности) остаются без изменений
    return (Z, *new_parameters)

# Размер продукта в KSLOC, тысячах строк исходного кода.
SIZE = (7.2, 0.8, 0.9)

# Возведение в степень E_constant нечеткого числа SIZE
SIZE_power_E = power_fuzzy_number_with_constant(SIZE, E_constant)

print(f"При рассчитанном выше показателе степени E {E_constant}, а также размере продукта в {SIZE} KSLOC, SIZE^E принимает значение {SIZE_power_E}")


При рассчитанном выше показателе степени E 1.071, а также размере продукта в (7.2, 0.8, 0.9) KSLOC, SIZE^E принимает значение (8.28, 0.79, 0.89)


In [ ]:
# Вычисление PM = 2.94 * (SIZE**(E)) * (EM_multiply)

def multiply_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X  # Извлекаем значение и параметры X
    y_value, *y_parameters = Y  # Извлекаем значение и параметры Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for x_param in x_parameters:
        for y_param in y_parameters:
            # Вычисление параметров для Z
            z_param = round(x_param * y_param, 2)
            result_parameters.append(z_param)

    # Вычисление значения Z
    Z_value = round(x_value * y_value, 3)

    return (Z_value, *result_parameters)

# Умножение дискретного числа на колеблющееся нечеткое число
multiplied_A_SIZE_power_E = multiply_fuzzy_number_with_constant(SIZE_power_E, 2.94)

# Умножение колеблющихся нечетких чисел
PM = multiply_discrete_fuzzy_numbers(multiplied_A_SIZE_power_E, EM_multiply_processed_result)
print(f"При рассчитанном выше показателе степени E {E_constant}, а также размере продукта в {SIZE} KSLOC, оценка трудоемкости проекта PM принимает значение {PM} чел*мес")


При рассчитанном выше показателе степени E 1.071, а также размере продукта в (7.2, 0.8, 0.9) KSLOC, оценка трудоемкости проекта PM принимает значение (13.486, 0.21, 0.23, 0.24, 0.26, 0.27, 0.3, 0.31, 0.33, 0.34, 0.37, 0.38, 0.42, 0.43, 0.48, 0.21, 0.23, 0.24, 0.26, 0.27, 0.3, 0.31, 0.33, 0.34, 0.37, 0.38, 0.42, 0.43, 0.48) чел*мес


In [ ]:
# Дополнение к коду для обработки результата
PM_processed_result = process_fuzzy_result(PM)

# Вывод обработанного результата
print(f"Обработанный результат PM: {PM_processed_result}")

Обработанный результат PM: (13.486, 0.21, 0.23, 0.24, 0.26, 0.27, 0.3, 0.31, 0.33, 0.34, 0.37, 0.38, 0.42, 0.43, 0.48)


# Анализ точек сценариев (Use Case Point, *UСP*)

**Четкая модель *UС*P**

In [ ]:
def UAW (A1, A2, A3):
    UAW = 1 * A1 + 2 * A2 + 3 * A3
    return UAW

In [ ]:
A1 = 2 # Количество простых действующих лиц
A2 = 2 # Количество средних действующих лиц
A3 = 3 # Количество сложных действующих лиц
print(f"При {A1} простых, {A2} средних и {A3} сложных действующих лицах вес действующих лиц без поправок UАW принимает значение {UAW(A1, A2, A3)}")

При 2 простых, 2 средних и 3 сложных действующих лицах вес действующих лиц без поправок UАW принимает значение 15


In [ ]:
def UUCW (V1, V2, V3):
  UUCW = 5 * V1 + 10 * V2 + 15 * V3
  return UUCW

In [ ]:
V1 = 0 # Количество простых вариантов использования
V2 = 7 # Количество средних вариантов использования
V3 = 0 # Количество сложных вариантов использования
print(f"При {V1} простых, {V2} средних, {V3} сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение {UUCW(V1, V2, V3)}")


При 0 простых, 7 средних, 0 сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение 70


In [ ]:
UUCP = UAW (A1, A2, A3) + UUCW (V1, V2, V3)

In [ ]:
print(f"При A = {UAW (A1, A2, A3)} и сложности вариантов использования {UUCW (V1, V2, V3)}, показатель UUCP принимает значение {UUCP}")

При A = 15 и сложности вариантов использования 70, показатель UUCP принимает значение 85


In [ ]:
def ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13):
  STi = 2 * T1 + 1 * T2 + 1 * T3 + 1 * T4 + 1 * T5 + 0.5 * T6 + 0.5 * T7 + 2 * T8 + 1 * T9 + 1 * T10 + 1 * T11 + 1 * T12 + 1 * T13
  return STi

In [ ]:
T1 = 4   # Распределенная система, показатель от 0 до 5 включительно
T2 = 3   # Высокая производительность (пропускная способность), показатель от 0 до 5 включительно
T3 = 5   # Работа конечных пользователей в режиме он-лайн, показатель от 0 до 5 включительно
T4 = 1   # Сложная обработка данных, показатель от 0 до 5 включительно
T5 = 0   # Повторное использование кода, показатель от 0 до 5 включительно
T6 = 5   # Простота установки, показатель от 0 до 5 включительно
T7 = 2   # Простота использования, показатель от 0 до 5 включительно
T8 = 0   # Переносимость, показатель от 0 до 5 включительно
T9 = 4   # Простота внесения изменений, показатель от 0 до 5 включительно
T10 = 5  # Параллелизм, показатель от 0 до 5 включительно
T11 = 3  # Специальные требования к безопасности, показатель от 0 до 5 включительно
T12 = 5  # Непосредственный доступ к системе со стороны внешних пользователей, показатель от 0 до 5 включительно
T13 = 1  # Специальные требования к обучению пользователей, показатель от 0 до 5 включительно
ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)
print(f"При вышеуказанных параметрах T1-T13, взвешенная сумма показателей STi принимает значение {ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)}")

При вышеуказанных параметрах T1-T13, взвешенная сумма показателей STi принимает значение 38.5


In [ ]:
TCF = 0.6 + (0.01 * ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13))

In [ ]:
print(f"При вышеуказанных параметрах T1-T13, показатель технической сложности проекта (TCF) принимает значение {TCF}")

При вышеуказанных параметрах T1-T13, показатель технической сложности проекта (TCF) принимает значение 0.985


In [ ]:
def SF(F1, F2, F3, F4, F5, F6, F7, F8):
  SFi = 1.5 * F1 + 0.5 * F2 + 1 * F3 + 0.5 * F4 + 1 * F5 + 2 * F6 - 1 * F7 - 1 * F8
  return SFi

In [ ]:
F1 = 4   # Знакомство с технологией, показатель от 0 до 5 включительно
F2 = 3   # Опыт разработки приложений, показатель от 0 до 5 включительно
F3 = 5   # Опыт использования объектно-ориентированного подхода, показатель от 0 до 5 включительно
F4 = 1   # Наличие ведущего аналитика, показатель от 0 до 5 включительно
F5 = 0   # Мотивация, показатель от 0 до 5 включительно
F6 = 5   # Стабильность требований, показатель от 0 до 5 включительно
F7 = 5   # Частичная занятость, показатель от 0 до 5 включительно
F8 = 0   # Сложные языки программирования, показатель от 0 до 5 включительно
SF(F1, F2, F3, F4, F5, F6, F7, F8)
print(f"При вышеуказанных параметрах F1-F8, взвешенная сумма показателей SFi принимает значение {SF(F1, F2, F3, F4, F5, F6, F7, F8)}")

При вышеуказанных параметрах F1-F8, взвешенная сумма показателей SFi принимает значение 18.0


In [ ]:
EF = 1.4 + (-0.03 * SF(F1, F2, F3, F4, F5, F6, F7, F8))

In [ ]:
print(f"При вышеуказанных параметрах F1-F8, показатель уровня квалификации разработчиков (EF) принимает значение {round(EF, 2)}")

При вышеуказанных параметрах F1-F8, показатель уровня квалификации разработчиков (EF) принимает значение 0.86


In [ ]:
UCP = UUCP * TCF * EF

In [ ]:
print(f"При вышеуказанных параметрах UUCP, TCF и EF, окончательное значение UCP равно {round(UCP, 2)}")

При вышеуказанных параметрах UUCP, TCF и EF, окончательное значение UCP равно 72.0


В качестве начального значения предлагается использовать 20 чел.-ч. на одну *UCP*. Эта величина може уточняться с учетом опыта разработчиков. [Коротаев А.Н., Марчев Д.В. Экономика программной инженерии]

# Нечеткая модель *UCP*. Применение трапециевидных нечетких чисел 2 типа

Нечеткие трапециевидные числа второго типа имеют две ФП - верхнюю и нижнюю для ИНМ2Т и функции принадлежности и непринадлежности для интуиционистских НМ, отражающие сомнения эксперта в оценках границ нечеткости, т.е. правая и левая границы нечеткости имеют по 2 значения. Левая граница - это минимальное значение нечеткости, правая, соответственно, максимальное.

Все коэффициенты и присваиваемые значения, являющиеся константами, в данном методе могут быть нечеткими. Для корректной работы модели важно соблюдать пропорции между коэффициентами (если они подвергаются корректировке - это должно быть обусловлено особенностями практического применения модели для конкретного проекта).

In [ ]:
# Функция умножения трапециевидного нечеткого числа (интуиционистского или интервального 2 типа) на константу
def multiply_fuzzy_number_by_constant(fuzzy_number, constant):
    # Умножение нечеткого числа на константу
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    if constant < 0:
        # Умножение всех координат на константу в обратном порядке
        new_X = (
            (x4 * constant, x3 * constant, x2 * constant, x1 * constant),
            (x8 * constant, x7 * constant, x6 * constant, x5 * constant)
        )
    else:
        # Умножение всех координат на константу в обычном порядке
        new_X = (
            (x1 * constant, x2 * constant, x3 * constant, x4 * constant),
            (x5 * constant, x6 * constant, x7 * constant, x8 * constant)
        )
    return new_X

In [ ]:
# Функция суммы двух трапециевидных нечетких чисел (интуиционистских или интервальных 2 типа)
def add_intuitionistic_trapezoidal_fuzzy_numbers(fuzzy_number1, fuzzy_number2):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number1
    (y1, y2, y3, y4), (y5, y6, y7, y8) = fuzzy_number2
    return ((x1 + y1, x2 + y2, x3 + y3, x4 + y4),
            (x5 + y5, x6 + y6, x7 + y7, x8 + y8))

In [ ]:
# Функция произведения двух трапециевидных нечетких чисел (интуиционистских или интервальных 2 типа)
def multiply_intuitionistic_trapezoidal_fuzzy_numbers(X, Y):
    # Распаковка параметров интервальных трапециевидных чисел 2 типа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = X
    (y1, y2, y3, y4), (y5, y6, y7, y8) = Y

    # Вычисление координат для произведения с округлением
    z1 = round(x2 * y1 - x2 * y2 + x1 * y2, 2)
    z2 = round(x2 * y2, 2)
    z3 = round(x3 * y3, 2)
    z4 = round(x3 * y4 - x3 * y3 + y3 * x4, 2)

    z5 = round(x6 * y5 - x6 * y6 + x5 * y6, 2)
    z6 = round(x6 * y6, 2)
    z7 = round(x7 * y7, 2)
    z8 = round(x7 * y8 - x7 * y7 + y7 * x8, 2)

    return ((z1, z2, z3, z4), (z5, z6, z7, z8))

In [ ]:
# Функция вычисления среднего арифметического дефаззифицированных значений двух функция принадлежности
def calculate_average(defuzzified_values):
    # Извлекаем значения из кортежа
    defuzzified_upper, defuzzified_lower = defuzzified_values
    # Вычисляем среднее арифметическое
    average = round((defuzzified_upper + defuzzified_lower) / 2, 3)
    return average

In [ ]:
# Расчет коэффициента UAW: UAW= 1 * A1 + 2 * A2 + 3 * A3

def UAW (A1, A2, A3):
    # Умножаем на соответствующие константы
    A1_weighted = multiply_fuzzy_number_by_constant(A1, 1)
    A2_weighted = multiply_fuzzy_number_by_constant(A2, 2)
    A3_weighted = multiply_fuzzy_number_by_constant(A3, 3)

    # Складываем результаты
    Ai = add_intuitionistic_trapezoidal_fuzzy_numbers(A1_weighted, A2_weighted)
    Ai = add_intuitionistic_trapezoidal_fuzzy_numbers(Ai, A3_weighted)

    return Ai

In [ ]:
A1 = ((2, 2, 2, 2),(2, 2, 2, 2)) # Количество простых действующих лиц
A2 = ((2, 2, 2, 2),(2, 2, 2, 2)) # Количество средних действующих лиц
A3 = ((3, 3, 3, 3),(3, 3, 3, 3)) # Количество сложных действующих лиц

print(f"При {A1} простых, {A2} средних и {A3} сложных действующих лицах коэффициент UAW принимает значение {UAW(A1, A2, A3)}")

При ((2, 2, 2, 2), (2, 2, 2, 2)) простых, ((2, 2, 2, 2), (2, 2, 2, 2)) средних и ((3, 3, 3, 3), (3, 3, 3, 3)) сложных действующих лицах коэффициент UAW принимает значение ((15, 15, 15, 15), (15, 15, 15, 15))


In [ ]:
# Вычисляем UUCW = const1 * V1 + const2 * V2 + const3 * V3

# задаем удельные веса вариантов использования
const1 = ((3.5, 4.5, 5.5, 6.5),(4.0, 4.5, 5.5, 6.0))         # Удельный вес простого варианта использования
const2 = ((8.5, 9.5, 10.5, 11.5),(9.0, 9.5, 10.5, 11.0))     # Удельный вес среднего варианта использования
const3 = ((13.5, 14.5, 15.5, 16.5),(14.0, 14.5, 15.5, 16.0)) # Удельный вес сложного варианта использования


def UUCW(V1, V2, V3):
    # Умножаем const1 на V1
    V1_weighted = multiply_intuitionistic_trapezoidal_fuzzy_numbers(const1, V1)
    # Умножаем const2 на V2
    V2_weighted = multiply_intuitionistic_trapezoidal_fuzzy_numbers(const2, V2)
    # Умножаем const3 на V3
    V3_weighted = multiply_intuitionistic_trapezoidal_fuzzy_numbers(const3, V3)

    # Суммируем 3 взвешенныp нечеткие числа
    UUCWi = add_intuitionistic_trapezoidal_fuzzy_numbers(V1_weighted, V2_weighted)
    UUCWi = add_intuitionistic_trapezoidal_fuzzy_numbers(UUCWi, V3_weighted)

    return UUCWi

In [ ]:
V1 = ((0, 0, 0, 0), (0, 0, 0, 0)) # Количество простых вариантов использования
V2 = ((7, 7, 7, 7), (7, 7, 7, 7)) # Количество средних вариантов использования
V3 = ((0, 0, 0, 0), (0, 0, 0, 0)) # Количество сложных вариантов использования
print(f"При {V1} простых, {V2} средних, {V3} сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение {UUCW(V1, V2, V3)}")


При ((0, 0, 0, 0), (0, 0, 0, 0)) простых, ((7, 7, 7, 7), (7, 7, 7, 7)) средних, ((0, 0, 0, 0), (0, 0, 0, 0)) сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение ((59.5, 66.5, 73.5, 80.5), (63.0, 66.5, 73.5, 77.0))


In [ ]:
# UUCP = UAW (A1, A2, A3) + UUCW (V1, V2, V3)
UAW_result = UAW (A1, A2, A3)
UUCW_result = UUCW (V1, V2, V3)

# Сложение результатов UAW и UUCW
UUCP = add_intuitionistic_trapezoidal_fuzzy_numbers(UAW_result, UUCW_result)

In [ ]:
print(f"При UAW = {UAW (A1, A2, A3)} и UUCW {UUCW (V1, V2, V3)}, показатель UUCP принимает значение {UUCP}")

При UAW = ((15, 15, 15, 15), (15, 15, 15, 15)) и UUCW ((59.5, 66.5, 73.5, 80.5), (63.0, 66.5, 73.5, 77.0)), показатель UUCP принимает значение ((74.5, 81.5, 88.5, 95.5), (78.0, 81.5, 88.5, 92.0))


In [ ]:
# Вычисляем STi = 2 * T1 + 1 * T2 + 1 * T3 + 1 * T4 + 1 * T5 + 0.5 * T6 + 0.5 * T7 + 2 * T8 + 1 * T9 + 1 * T10 + 1 * T11 + 1 * T12 + 1 * T13

def ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13):
    # Вычисляем взвешенные нечеткие трапециевидные числа
    STi = (
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T1, 2),
                                                      multiply_fuzzy_number_by_constant(T2, 1)),
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T3, 1),
                                                      multiply_fuzzy_number_by_constant(T4, 1)),
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T5, 1),
                                                      multiply_fuzzy_number_by_constant(T6, 0.5)),
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T7, 0.5),
                                                      multiply_fuzzy_number_by_constant(T8, 2)),
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T9, 1),
                                                      multiply_fuzzy_number_by_constant(T10, 1)),
        add_intuitionistic_trapezoidal_fuzzy_numbers(multiply_fuzzy_number_by_constant(T11, 1),
                                                      multiply_fuzzy_number_by_constant(T12, 1)),
        multiply_fuzzy_number_by_constant(T13, 1)
    )

    # Складываем все результаты
    STi_final = add_intuitionistic_trapezoidal_fuzzy_numbers(add_intuitionistic_trapezoidal_fuzzy_numbers(STi[0], STi[1]),
                                                              add_intuitionistic_trapezoidal_fuzzy_numbers(STi[2], STi[3]))
    STi_final = add_intuitionistic_trapezoidal_fuzzy_numbers(STi_final,
                                                              add_intuitionistic_trapezoidal_fuzzy_numbers(STi[4], STi[5]))
    STi_final = add_intuitionistic_trapezoidal_fuzzy_numbers(STi_final, STi[6])

    return STi_final


In [ ]:
T1 = ((2.5, 3.5, 4.5, 5.5), (3.0, 3.5, 4.5, 5.0))   # Распределенная система, показатель от 0 до 5 включительно
T2 = ((1.5, 2.5, 3.5, 4.5), (2.0, 2.5, 3.5, 4.0))   # Высокая производительность (пропускная способность), показатель от 0 до 5 включительно
T3 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Работа конечных пользователей в режиме он-лайн, показатель от 0 до 5 включительно
T4 = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))   # Сложная обработка данных, показатель от 0 до 5 включительно
T5 = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Повторное использование кода, показатель от 0 до 5 включительно
T6 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Простота установки, показатель от 0 до 5 включительно
T7 = ((0.5, 1.5, 2.5, 3.5), (1.0, 1.5, 2.5, 3.0))   # Простота использования, показатель от 0 до 5 включительно
T8 = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Переносимость, показатель от 0 до 5 включительно
T9 = ((2.5, 3.5, 4.5, 5.5), (3.0, 3.5, 4.5, 5.0))   # Простота внесения изменений, показатель от 0 до 5 включительно
T10 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))  # Параллелизм, показатель от 0 до 5 включительно
T11 = ((1.5, 2.5, 3.5, 4.5), (2.0, 2.5, 3.5, 4.0))  # Специальные требования к безопасности, показатель от 0 до 5 включительно
T12 = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))  # Непосредственный доступ к системе со стороны внешних пользователей, показатель от 0 до 5 включительно
T13 = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))  # Специальные требования к обучению пользователей, показатель от 0 до 5 включительно
ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)
print(f"При вышеуказанных параметрах T1-T13, взвешенная сумма показателей STi принимает значение {ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)}")

При вышеуказанных параметрах T1-T13, взвешенная сумма показателей STi принимает значение ((23.0, 33.0, 44.0, 58.0), (27.5, 33.0, 44.0, 51.0))


In [ ]:
# Функция для округления нечеткого числа до заданного количества знаков после запятой
def round_fuzzy_number(fuzzy_number):
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number
    return (
        (round(x1, 3), round(x2, 3), round(x3, 3), round(x4, 3)),
        (round(x5, 3), round(x6, 3), round(x7, 3), round(x8, 3))
    )

# Вычисление TCF
def calculate_TCF(ST_result):
    # Умножение ST_result на 0.01
    multiplied_result = multiply_fuzzy_number_by_constant(ST_result, 0.01)

    # Константа 0.6 представляется как нечеткое трапециевидное число
    constant_0_6 = ((0.6, 0.6, 0.6, 0.6), (0.6, 0.6, 0.6, 0.6))

    # Сложение результата умножения с константой 0.6
    final_result = add_intuitionistic_trapezoidal_fuzzy_numbers(multiplied_result, constant_0_6)

    return final_result

# Вычисление ST
ST_result = ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)

# Вычисление TCF
TCF_result = calculate_TCF(ST_result)

# Округление итогового результата TCF до 3 знаков после запятой
rounded_TCF_result = round_fuzzy_number(TCF_result)

In [ ]:
print(f"При вышеуказанных параметрах T1-T13, показатель технической сложности проекта (TCF) принимает значение {rounded_TCF_result}")

При вышеуказанных параметрах T1-T13, показатель технической сложности проекта (TCF) принимает значение ((0.83, 0.93, 1.04, 1.18), (0.875, 0.93, 1.04, 1.11))


In [ ]:
# Вычисляем SFi = 1.5 * F1 + 0.5 * F2 + 1 * F3 + 0.5 * F4 + 1 * F5 + 2 * F6 - 1 * F7 - 1 * F8

def SFi(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i):
    # Умножаем каждое нечеткое число на соответствующий коэффициент
    F1i_weighted = multiply_fuzzy_number_by_constant(F1i, 1.5)
    F2i_weighted = multiply_fuzzy_number_by_constant(F2i, 0.5)
    F3i_weighted = multiply_fuzzy_number_by_constant(F3i, 1)
    F4i_weighted = multiply_fuzzy_number_by_constant(F4i, 0.5)
    F5i_weighted = multiply_fuzzy_number_by_constant(F5i, 1)
    F6i_weighted = multiply_fuzzy_number_by_constant(F6i, 2)
    F7i_weighted = multiply_fuzzy_number_by_constant(F7i, -1)
    F8i_weighted = multiply_fuzzy_number_by_constant(F8i, -1)

    # Суммируем все взвешенные нечеткие числа
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(F1i_weighted, F2i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F3i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F4i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F5i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F6i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F7i_weighted)
    SFii = add_intuitionistic_trapezoidal_fuzzy_numbers(SFii, F8i_weighted)

    return SFii

In [ ]:
def calculate_UFP(*params):
    UFP = params[0]
    for param in params[1:]:
        UFP = add_intuitionistic_trapezoidal_fuzzy_numbers(UFP, param)
    return UFP

In [ ]:
F1i = ((2.5, 3.5, 4.5, 5.5), (3.0, 3.5, 4.5, 5.0))   # Знакомство стехнологией, показатель от 0 до 5 включительно
F2i = ((1.5, 2.5, 3.5, 4.5), (2.0, 2.5, 3.5, 4.0))   # Опыт разработки приложений, показатель от 0 до 5 включительно
F3i = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Опыт использования объектно-ориентированного подхода, показатель от 0 до 5 включительно
F4i = ((0.0, 0.5, 1.5, 2.5), (0.0, 0.5, 1.5, 2.0))   # Наличие ведущего аналитика, показатель от 0 до 5 включительно
F5i = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Мотивация, показатель от 0 до 5 включительно
F6i = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Стабильность требований, показатель от 0 до 5 включительно
F7i = ((3.5, 4.5, 5.5, 6.5), (4.0, 4.5, 5.5, 6.0))   # Частичная занятость, показатель от 0 до 5 включительно
F8i = ((0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.0, 0.5))   # Сложные языки программирования, показатель от 0 до 5 включительно
SFi(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i)
print(f"При вышеуказанных параметрах F1i-F8i, взвешенная сумма показателей Fi принимает значение {SFi(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i)}")

При вышеуказанных параметрах F1i-F8i, взвешенная сумма показателей Fi принимает значение ((7.5, 14.75, 21.25, 28.75), (11.0, 14.75, 21.25, 25.0))


In [ ]:
# Вычисление уровня квалификации разработчиков EF
def calculate_EF(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i):
    # Вычисляем SFi
    SFii = SFi(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i)
    # Умножаем SFi на -0.03
    weighted_SFi = multiply_fuzzy_number_by_constant(SFii, -0.03)

    # Константа 1.4 в виде нечеткого числа
    constant_1_4 = ((1.4, 1.4, 1.4, 1.4), (1.4, 1.4, 1.4, 1.4))

    # Сложение 1.4 и (-0.03 * SFi)
    EF = add_intuitionistic_trapezoidal_fuzzy_numbers(constant_1_4, weighted_SFi)

    # Округление результата до 3 знаков после запятой
    EF_rounded = round_fuzzy_number(EF)

    return EF_rounded

In [ ]:
print(f"При вышеуказанных параметрах F1-F8, показатель уровня квалификации разработчиков (EF) принимает значение {calculate_EF(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i)}")

При вышеуказанных параметрах F1-F8, показатель уровня квалификации разработчиков (EF) принимает значение ((0.537, 0.762, 0.957, 1.175), (0.65, 0.762, 0.957, 1.07))


In [ ]:
# Вычисление итогового значения UCP

# Вычисляем произведение UUCP и TCF
UUCP_result = UUCP
TCF_result = rounded_TCF_result

# Умножаем UUCP на TCF
UCP_intermediate = multiply_intuitionistic_trapezoidal_fuzzy_numbers(UUCP_result, TCF_result)

# Умножаем полученное произведение на EF
EF_result = calculate_EF(F1i, F2i, F3i, F4i, F5i, F6i, F7i, F8i)
UCP_final = multiply_intuitionistic_trapezoidal_fuzzy_numbers(UCP_intermediate, EF_result)

# Округляем итоговое значение UCP_final до 3 знаков после запятой
UCP_final_rounded = round_fuzzy_number(UCP_final)

In [ ]:
print(f"При вышеуказанных параметрах UUCP, TCF и EF, окончательное значение UCP равно {UCP_final_rounded}")

При вышеуказанных параметрах UUCP, TCF и EF, окончательное значение UCP равно ((29.53, 57.76, 88.08, 126.97), (43.37, 57.76, 88.08, 107.9))


Для перехода от нечетких значений к четким, применим операцию альфа-среза. В результате получим четкий интервал (отрезок) значений из области определения нечеткого трапециевидного числа 2-го типа, который будет соответствовать единственному значению функции принадлежности, заданному уровнем альфа-среза.

In [ ]:
# Функция вычисления альфа-среза
def alpha_cut(fuzzy_number, alpha):
    # Распаковка параметров нечеткого числа
    (x1, x2, x3, x4), (x5, x6, x7, x8) = fuzzy_number

    # Вычисление концов верхнего интервала альфа-среза
    upper_start = alpha * x2 + (1 - alpha) * x1
    upper_end = alpha * x3 + (1 - alpha) * x4

    # Вычисление концов нижнего интервала альфа-среза
    lower_start = alpha * x6 + (1 - alpha) * x5
    lower_end = alpha * x7 + (1 - alpha) * x8

    # Округляем значения до 3 знаков после запятой
    upper_start = round(upper_start, 3)
    upper_end = round(upper_end, 3)
    lower_start = round(lower_start, 3)
    lower_end = round(lower_end, 3)

    # Возвращаем альфа-срез в виде нечеткого числа
    return ((upper_start, upper_end), (lower_start, lower_end))

Зададим уровень альфа-среза равным 0.8. Значение альфа-среза - это уровень уверенности стейкхолдеров в полученной оценке итогового результата моделирования. Левая и права граница интервала (отрезка, являющегося результатом применения альфа-среза) - это минимальное (левая граница) и максимальное (правая граница) значения, которые может принимать результат моделирования с данной степенью уверенности.

In [ ]:
# Вычисление альфа-среза
alpha = 0.8
alpha_cut_result = alpha_cut(UCP_final_rounded, alpha)
print(f"Альфа-срез при альфа={alpha} для UCP_final_rounded {UCP_final_rounded} равен {alpha_cut_result}")

Альфа-срез при альфа=0.8 для UCP_final_rounded ((29.53, 57.76, 88.08, 126.97), (43.37, 57.76, 88.08, 107.9)) равен ((52.114, 95.858), (54.882, 92.044))


Другими словами, с 80% уверенностью можно утверждать, что величина окончательного значения *UCP* составит от 52.11 до 95.86 ед. в верхней функции принадлежности и от 54.88 до 92.04 ед. в нижней функции принадлежности.

Для приведения интервальных оценок к точечным результатам применяются методы усреднения, например, центроид системы двух точек, которым является является середина отрезка, соединяющего данные точки, т.е. среднее арифметическое левого и правого значения его координат (среднее минимума и максимума по оси абсцисс).

In [ ]:
# Расчет центроида системы двух точек
def centroid(alpha_cut_result):
    # Распаковка верхнего и нижнего отрезков альфа-среза
    (upper_start, upper_end), (lower_start, lower_end) = alpha_cut_result

    # Расчет среднего значения
    central_upper = round((upper_start + upper_end) / 2, 3)
    central_lower = round((lower_start + lower_end) / 2, 3)

    # Возвращаем результат в нужном формате
    return (central_upper, central_lower)

alpha_cut_result = alpha_cut(UCP_final_rounded, alpha)
central_result = centroid(alpha_cut_result)

print(f"Усредненные значения для UCP_final_rounded {UCP_final_rounded} при альфа={alpha} равны {central_result}")


Усредненные значения для UCP_final_rounded ((29.53, 57.76, 88.08, 126.97), (43.37, 57.76, 88.08, 107.9)) при альфа=0.8 равны (73.986, 73.463)


Усредненный (четкий) итоговый результат оценки трудоемкости проекта составит составляет 73,99 *UCP* по верхней функции принадлежности и 73,46 - по нижней.

In [ ]:
# Вычисляем среднее арифметическое усредненных значений
UCP_final_discrete = calculate_average(central_result)

print(f"Среднее значение трудоемкости по нечеткой модели составляет {UCP_final_discrete} UCP")

Среднее значение трудоемкости по нечеткой модели составляет 73.725 UCP


Итоговое усредненное четкое значение результата моделирования составит составляет 73,73 *UCP*.

# Нечеткая модель *UCP*. Применение колеблющихся нечетких чисел.

In [ ]:
# Функция для обработки результата - исключение повторов и упорядочивание по возрастанию значений функции принадлежности
def process_fuzzy_result(fuzzy_result):
    # Распаковка результата
    x_value, *parameters = fuzzy_result

    # Исключение повторяющихся значений и упорядочение по возрастанию
    unique_parameters = sorted(set(parameters))

    # Формирование нового кортежа с уникальными значениями
    processed_result = (x_value, *unique_parameters)

    return processed_result

In [ ]:
# Расчет коэффициента UAW: UAW = 1 * A1 + 2 * A2 + 3 * A3
# Функция для умножения дискретного колеблющегося нечеткого числа на константу
def multiply_fuzzy_number_with_constant(X, A):
    # Распаковка параметров дискретного нечеткого числа
    x, *parameters = X  # Извлекаем значение и параметры

    # Вычисление нового значения Z
    Z = round(A * x, 2)  # Умножение значения X на константу A

    # Вычисление новых параметров для Z
    new_parameters = [round(1 - (1 - param)**A, 2) for param in parameters]

    return round(Z, 2), new_parameters

# Входные данные
X1h = (2, 0.4, 0.5)  # Количество простых действующих лиц
A1 = 1  # Константа для умножения

X2h = (2, 0.4, 0.5)  # Количество средних действующих лиц
A2 = 2  # Константа для умножения

X3h = (3, 0.4, 0.5)  # Количество сложных действующих лиц
A3 = 3  # Константа для умножения

# Умножение нечеткого числа X1h на константу A1
result_value1, result_parameters1 = multiply_fuzzy_number_with_constant(X1h, A1)
# Умножение нечеткого числа X2h на константу A2
result_value2, result_parameters2 = multiply_fuzzy_number_with_constant(X2h, A2)
# Умножение нечеткого числа X3h на константу A3
result_value3, result_parameters3 = multiply_fuzzy_number_with_constant(X3h, A3)

# Объединение результатов в кортежи
final_result1 = (result_value1, *result_parameters1)
final_result2 = (result_value2, *result_parameters2)
final_result3 = (result_value3, *result_parameters3)

# Вывод результатов
print(f"Результат умножения нечеткого числа X1 на константу A1: {final_result1}")
print(f"Результат умножения нечеткого числа X2 на константу A2: {final_result2}")
print(f"Результат умножения нечеткого числа X3 на константу A3: {final_result3}")

Результат умножения нечеткого числа X1 на константу A1: (2, 0.4, 0.5)
Результат умножения нечеткого числа X2 на константу A2: (4, 0.64, 0.75)
Результат умножения нечеткого числа X3 на константу A3: (9, 0.78, 0.88)


In [ ]:
# Функция для вычисления суммы дискретных колеблющихся нечетких чисел
def add_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X
    y_value, *y_parameters = Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for xi in x_parameters:
        for yj in y_parameters:
            # Вычисление параметров для Z
            zij = round(xi + yj - xi * yj, 2)
            result_parameters.append(zij)

    # Вычисление значения Z
    Z = round(x_value + y_value, 2)

    return Z, result_parameters

# Сложение final_result1 и final_result2
sum_result1_value, sum_result1_parameters = add_discrete_fuzzy_numbers(final_result1, final_result2)

# Объединение результата в кортеж
final_result_sum1 = (sum_result1_value, *sum_result1_parameters)

# Сложение полученной суммы с final_result3
final_sum_value, final_sum_parameters = add_discrete_fuzzy_numbers(final_result_sum1, final_result3)

# Объединение итогового результата в кортеж
final_sum_result = (final_sum_value, *final_sum_parameters)

# Вывод результатов
print(f"Коэффициент UAW принимает значение: {final_sum_result}")


Коэффициент UAW принимает значение: (15, 0.95, 0.97, 0.97, 0.98, 0.96, 0.98, 0.97, 0.99)


In [ ]:
# Дополнение к коду для обработки результата
processed_result = process_fuzzy_result(final_sum_result)

# Вывод обработанного результата
print(f"Обработанный результат UAW: {processed_result}")


Обработанный результат UAW: (15, 0.95, 0.96, 0.97, 0.98, 0.99)


In [ ]:
# Функция произведения двух дискретных колеблющихся нечетких чисел
def multiply_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X  # Извлекаем значение и параметры X
    y_value, *y_parameters = Y  # Извлекаем значение и параметры Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for x_param in x_parameters:
        for y_param in y_parameters:
            # Вычисление параметров для Z
            z_param = round(x_param * y_param, 2)
            result_parameters.append(z_param)

    # Вычисление значения Z
    Z_value = round(x_value * y_value, 2)

    return (Z_value, *result_parameters)

In [ ]:
# Вычисляем UUCW = const1 * V1 + const2 * V2 + const3 * V3

# задаем удельные веса вариантов использования
const1 = (5, 0.7, 0.8)   # Удельный вес простого варианта использования
const2 = (10, 0.7, 0.8)  # Удельный вес среднего варианта использования
const3 = (15, 0.7, 0.8)  # Удельный вес сложного варианта использования

V1 = (0, 0.7, 0.8) # Количество простых вариантов использования
V2 = (7, 0.7, 0.8) # Количество средних вариантов использования
V3 = (0, 0.7, 0.8) # Количество сложных вариантов использования

# Умножаем const1 на V1
V1_weighted = multiply_discrete_fuzzy_numbers (const1, V1)
# Умножаем const2 на V2
V2_weighted = multiply_discrete_fuzzy_numbers (const2, V2)
# Умножаем const3 на V3
V3_weighted = multiply_discrete_fuzzy_numbers (const3, V3)

# Сложение V1_weighted и V2_weighted
sum_V1V2_result1_value, sum_V1V2_result1_parameters = add_discrete_fuzzy_numbers(V1_weighted, V2_weighted)

# Объединение результата в кортеж
final_V1V2_result_sum1 = (sum_V1V2_result1_value, *sum_V1V2_result1_parameters)

# Сложение полученной суммы с V3_weighted
final_sum_UUCW_value, final_sum_UUCW_parameters = add_discrete_fuzzy_numbers(final_V1V2_result_sum1, V3_weighted)

# Объединение итогового результата в кортеж
final_sum_UUCW_result = (final_sum_UUCW_value, *final_sum_UUCW_parameters)

print(f"При {V1} простых, {V2} средних, {V3} сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение {final_sum_UUCW_result}")

При (0, 0.7, 0.8) простых, (7, 0.7, 0.8) средних, (0, 0.7, 0.8) сложных вариантах использования вес вариантов использования без поправок UUCW принимает значение (70, 0.87, 0.89, 0.89, 0.91, 0.89, 0.9, 0.9, 0.92, 0.89, 0.9, 0.9, 0.92, 0.91, 0.92, 0.92, 0.94, 0.89, 0.9, 0.9, 0.92, 0.9, 0.92, 0.92, 0.93, 0.9, 0.92, 0.92, 0.93, 0.92, 0.93, 0.93, 0.94, 0.89, 0.9, 0.9, 0.92, 0.9, 0.92, 0.92, 0.93, 0.9, 0.92, 0.92, 0.93, 0.92, 0.93, 0.93, 0.94, 0.91, 0.92, 0.92, 0.94, 0.92, 0.93, 0.93, 0.94, 0.92, 0.93, 0.93, 0.94, 0.93, 0.94, 0.94, 0.95)


In [ ]:
# Дополнение к коду для обработки результата
processed_result_UUCW = process_fuzzy_result(final_sum_UUCW_result)

# Вывод обработанного результата
print(f"Обработанный результат UUCW: {processed_result_UUCW}")

Обработанный результат UUCW: (70, 0.87, 0.89, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95)


In [ ]:
# UUCP = UAW + UUCW

# Сложение processed_result и UCP1_result
UUCP_result_value, UUCP_result_parameters = add_discrete_fuzzy_numbers(processed_result, processed_result_UUCW)

# Объединение итогового результата в кортеж
UUCP_final_result = (UUCP_result_value, *UUCP_result_parameters)

# Вывод результата
print(f"Значение UUCP: {UUCP_final_result}")

Значение UUCP: (85, 0.99, 0.99, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.99, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0)


In [ ]:
# Дополнение к коду для обработки результата
UUCP_processed_result = process_fuzzy_result(UUCP_final_result)

# Вывод обработанного результата
print(f"Обработанный результат UUCP: {UUCP_processed_result}")

Обработанный результат UUCP: (85, 0.99, 1.0)


In [ ]:
# Вычисление STi = 2 * T1 + 1 * T2 + 1 * T3 + 1 * T4 + 1 * T5 + 0.5 * T6 + 0.5 * T7 + 2 * T8 + 1 * T9 + 1 * T10 + 1 * T11 + 1 * T12 + 1 * T13
# Функция суммы двух дискретных колеблющихся нечетких чисел
def add_discrete_fuzzy_numbers(X, Y):
    x_value, *x_parameters = X
    y_value, *y_parameters = Y
    result_parameters = []

    for xi in x_parameters:
        for yj in y_parameters:
            zij = round(xi + yj - xi * yj, 2)
            result_parameters.append(zij)

    Z = round(x_value + y_value, 3)
    return (Z, *result_parameters)

# Функция умножения дискретного колеблющегося нечеткого числа на константу
def multiply_fuzzy_number_with_constant(X, A):
    x, *parameters = X
    Z = round(A * x, 3)
    new_parameters = [round(1 - (1 - param)**A, 2) for param in parameters]
    return (Z, *new_parameters)

def ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13):
    weights = [2, 1, 1, 1, 1, 0.5, 0.5, 2, 1, 1, 1, 1, 1]
    inputs = [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]

    STi = (0,)

    # Присвоение имен для произведений
    results = []

    for weight, input_value in zip(weights, inputs):
        weighted_value = multiply_fuzzy_number_with_constant(input_value, weight)
        STi = add_discrete_fuzzy_numbers(STi, weighted_value)
        results.append(weighted_value)  # Сохраняем произведение

    return STi, results

# Значения показателей технической сложности проекта STi
T1 = (4, 0.4, 0.5)   # Исходное значение
T2 = (3, 0.4, 0.5)   # Исходное значение
T3 = (5, 0.4, 0.5)   # Исходное значение
T4 = (1, 0.4, 0.5)   # Исходное значение
T5 = (0, 0.4, 0.5)   # Исходное значение
T6 = (5, 0.4, 0.5)   # Исходное значение
T7 = (2, 0.4, 0.5)   # Исходное значение
T8 = (0, 0.4, 0.5)   # Исходное значение
T9 = (4, 0.4, 0.5)   # Исходное значение
T10 = (5, 0.4, 0.5)  # Исходное значение
T11 = (3, 0.4, 0.5)  # Исходное значение
T12 = (5, 0.4, 0.5)  # Исходное значение
T13 = (1, 0.4, 0.5)  # Исходное значение

# Вызов функции ST и вывод результата
result, weighted_results = ST(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)
# Присвоение имен результатам
T1h = weighted_results[0]   # Результат умножения (4, 0.4, 0.5) на 2
T2h = weighted_results[1]   # Результат умножения (3, 0.4, 0.5) на 1
T3h = weighted_results[2]   # Результат умножения (5, 0.4, 0.5) на 1
T4h = weighted_results[3]   # Результат умножения (1, 0.4, 0.5) на 1
T5h = weighted_results[4]   # Результат умножения (0, 0.4, 0.5) на 1
T6h = weighted_results[5]   # Результат умножения (5, 0.4, 0.5) на 0.5
T7h = weighted_results[6]   # Результат умножения (2, 0.4, 0.5) на 0.5
T8h = weighted_results[7]   # Результат умножения (0, 0.4, 0.5) на 2
T9h = weighted_results[8]   # Результат умножения (4, 0.4, 0.5) на 1
T10h = weighted_results[9]  # Результат умножения (5, 0.4, 0.5) на 1
T11h = weighted_results[10] # Результат умножения (3, 0.4, 0.5) на 1
T12h = weighted_results[11] # Результат умножения (5, 0.4, 0.5) на 1
T13h = weighted_results[12] # Результат умножения (1, 0.4, 0.5) на 1

# Выводим результаты умножения
for i, result in enumerate(weighted_results, start=1):
    print(f"T{i}h: {result}")


T1h: (8, 0.64, 0.75)
T2h: (3, 0.4, 0.5)
T3h: (5, 0.4, 0.5)
T4h: (1, 0.4, 0.5)
T5h: (0, 0.4, 0.5)
T6h: (2.5, 0.23, 0.29)
T7h: (1.0, 0.23, 0.29)
T8h: (0, 0.64, 0.75)
T9h: (4, 0.4, 0.5)
T10h: (5, 0.4, 0.5)
T11h: (3, 0.4, 0.5)
T12h: (5, 0.4, 0.5)
T13h: (1, 0.4, 0.5)


In [ ]:
# Список всех нечетких чисел
fuzzy_numbers = [T1h, T2h, T3h, T4h, T5h, T6h, T7h, T8h, T9h, T10h, T11h, T12h, T13h]

# Начинаем с первого нечеткого числа
current_sum = fuzzy_numbers[0]

# Поочередно складываем все нечеткие числа
for fuzzy_number in fuzzy_numbers[1:]:
    current_sum = add_discrete_fuzzy_numbers(current_sum, fuzzy_number)

# Вывод результата
print(f"Итоговая сумма всех нечетких чисел: {current_sum}")  # Вывод суммы


Итоговая сумма всех нечетких чисел: (38.5, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.99, 0.9

In [ ]:
# Узнаем количество элементов в итоговом кортеже
num_elements = len(current_sum)
print(f"Количество элементов в итоговом кортеже: {num_elements}")  # Вывод количества элементов

Количество элементов в итоговом кортеже: 8193


In [ ]:
# Дополнение к коду для обработки результата
# Присвоение обработанного результата переменной STih
STih = process_fuzzy_result(current_sum)

# Вывод значения STih
print(f"Значение STih: {STih}")

Значение STih: (38.5, 0.99, 1.0)


In [ ]:
# Вычисление TCF = 0.6 + (0.01 * STih)

def add_fuzzy_number_with_constant(X, A):
    # Распаковка параметров нечеткого числа
    x, *membership_degrees = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = x + A  # Сумма значения X и константы A

    # Параметры (степени принадлежности) остаются без изменений
    return (round(Z, 3), *membership_degrees)


# Умножаем STih на 0.01
multiplied_result = multiply_fuzzy_number_with_constant(STih, 0.01)

# Теперь прибавляем 0.6 к результату
TCF = add_fuzzy_number_with_constant(multiplied_result, 0.6)

# Вывод результата TCF
print(f"Значение TCF: {TCF}")

Значение TCF: (0.985, 0.05, 1.0)


In [ ]:
# Вычисление SFi = 1.5 * F1 + 0.5 * F2 + 1 * F3 + 0.5 * F4 + 1 * F5 + 2 * F6 - 1 * F7 - 1 * F8
# Сначала умножим все F1-F8 на соответствующие коэффициенты с положительным знаком

def add_discrete_fuzzy_numbers(X, Y):
    x_value, *x_parameters = X
    y_value, *y_parameters = Y
    result_parameters = []

    for xi in x_parameters:
        for yj in y_parameters:
            zij = round(xi + yj - xi * yj, 2)
            result_parameters.append(zij)

    Z = round(x_value + y_value, 2)
    return (Z, *result_parameters)
def SF(F1, F2, F3, F4, F5, F6, F7, F8):
    weights = [1.5, 0.5, 1, 0.5, 1, 2, 1, 1]
    inputs = [F1, F2, F3, F4, F5, F6, F7, F8]

    SFi = (0,)

    # Присвоение имен для произведений
    results = []

    for weight, input_value in zip(weights, inputs):
        weighted_value = multiply_fuzzy_number_with_constant(input_value, weight)
        SFi = add_discrete_fuzzy_numbers(SFi, weighted_value)
        results.append(weighted_value)  # Сохраняем произведение

    return SFi, results  # Возвращаем итоговое значение и все произведения

# Вводим показатели уровня квалификации разработчиков
F1 = (4, 0.5, 0.6)   #Знакомство с технологией, показатель от 0 до 5 включительно
F2 = (3, 0.5, 0.6)   #Опыт разработки приложений, показатель от 0 до 5 включительно
F3 = (5, 0.5, 0.6)   #Опыт использования объектно-ориентированного подхода, показатель от 0 до 5 включительно
F4 = (1, 0.5, 0.6)   #Наличие ведущего аналитика, показатель от 0 до 5 включительно
F5 = (0, 0.5, 0.6)   #Мотивация, показатель от 0 до 5 включительно
F6 = (5, 0.5, 0.6)   #Стабильность требований, показатель от 0 до 5 включительно
F7 = (5, 0.5, 0.6)   #Частичная занятость, показатель от 0 до 5 включительно
F8 = (0, 0.5, 0.6)   #Сложные языки программирования, показатель от 0 до 5 включительно

# Вызов функции SF и вывод результата
result, weighted_results = SF(F1, F2, F3, F4, F5, F6, F7, F8)
# Присвоение имен результатам
F1h = weighted_results[0]  # Результат умножения (4, 0.5, 0.6) на 1.5
F2h = weighted_results[1]  # Результат умножения (3, 0.5, 0.6) на 0.5
F3h = weighted_results[2]  # Результат умножения (5, 0.5, 0.6) на 1
F4h = weighted_results[3]  # Результат умножения (1, 0.5, 0.6) на 0.5
F5h = weighted_results[4]  # Результат умножения (0, 0.5, 0.6) на 1
F6h = weighted_results[5]  # Результат умножения (5, 0.5, 0.6) на 2
F7h = weighted_results[6]  # Результат умножения (5, 0.5, 0.6) на 1
F8h = weighted_results[7]  # Результат умножения (0, 0.5, 0.6) на 1


# Выводим результаты умножения
for i, result in enumerate(weighted_results, start=1):
    print(f"F{i}h: {result}")


F1h: (6.0, 0.65, 0.75)
F2h: (1.5, 0.29, 0.37)
F3h: (5, 0.5, 0.6)
F4h: (0.5, 0.29, 0.37)
F5h: (0, 0.5, 0.6)
F6h: (10, 0.75, 0.84)
F7h: (5, 0.5, 0.6)
F8h: (0, 0.5, 0.6)


In [ ]:
# Суммируемм все слагаемые, у которых коэффициенты в итоговой сумме SFi имеют положительный знак (F1h - F6h)
# Функция для сложения дискретных колеблющихся нечетких чисел
def add_discrete_fuzzy_numbers(X, Y):
    x_value, *x_parameters = X
    y_value, *y_parameters = Y
    result_parameters = []

    for xi in x_parameters:
        for yj in y_parameters:
            zij = round(xi + yj - xi * yj, 3)
            result_parameters.append(zij)

    Z = round(x_value + y_value, 3)
    return (Z, *result_parameters)
# Список всех нечетких чисел
fuzzy_numbers = [F1h, F2h, F3h, F4h, F5h, F6h]

# Начинаем с первого нечеткого числа
current_sum = fuzzy_numbers[0]

# Поочередно складываем все нечеткие числа
for fuzzy_number in fuzzy_numbers[1:]:
    current_sum = add_discrete_fuzzy_numbers(current_sum, fuzzy_number)

# Вывод результата
print(f"Итоговая сумма всех нечетких чисел: {current_sum}")


Итоговая сумма всех нечетких чисел: (23.0, 0.989, 0.993, 0.991, 0.994, 0.99, 0.994, 0.992, 0.995, 0.991, 0.994, 0.993, 0.996, 0.992, 0.995, 0.994, 0.996, 0.99, 0.994, 0.992, 0.995, 0.992, 0.995, 0.993, 0.996, 0.992, 0.995, 0.994, 0.996, 0.993, 0.996, 0.994, 0.996, 0.992, 0.995, 0.994, 0.996, 0.993, 0.996, 0.994, 0.996, 0.994, 0.996, 0.995, 0.997, 0.994, 0.996, 0.996, 0.997, 0.993, 0.996, 0.994, 0.996, 0.994, 0.996, 0.995, 0.997, 0.994, 0.996, 0.996, 0.997, 0.995, 0.997, 0.996, 0.997)


In [ ]:
# Узнаем количество элементов в итоговом кортеже
num_elements = len(current_sum)
print(f"Количество элементов в итоговом кортеже: {num_elements}")  # Вывод количества элементов

Количество элементов в итоговом кортеже: 65


In [ ]:
# А теперь от суммы первых 6 слагаемых отнимем два последних слагаемых, у которых коэффициенты имеют знак "-" - это F7h и F8h
# Определяем дискретные колеблющиеся нечеткие числа
F16h = current_sum
F7h = (5, 0.5, 0.6)
F8h = (0, 0.5, 0.6)

def difference_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X
    y_value, *y_parameters = Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for xi in x_parameters:
        for yj in y_parameters:
            # Условие для вычисления параметров для Z
            if xi >= yj and yj != 1:
                zij = round((xi - yj) / (1 - yj), 2)
            else:
                zij = 0  # Если условие не выполняется, zij = 0
            result_parameters.append(zij)

    # Вычисление значения Z
    Z = round(x_value - y_value, 2)

    return (Z, *result_parameters)

# Список всех нечетких чисел
fuzzy_numbers = [F16h, F7h, F8h]

# Начинаем с первого нечеткого числа
current_difference = fuzzy_numbers[0]

# Поочередно складываем все нечеткие числа
for fuzzy_number in fuzzy_numbers[1:]:
    current_difference = difference_discrete_fuzzy_numbers(current_difference, fuzzy_number)

# Вывод результата
print(f"Итоговая разность всех нечетких чисел: {current_difference}")


Итоговая разность всех нечетких чисел: (18.0, 0.96, 0.95, 0.94, 0.92, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.94, 0.92, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.94, 0.92, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 0.97, 0.98, 0.97, 0.96, 0.95, 0.98, 0.97, 0.98, 

In [ ]:
# Узнаем количество элементов в итоговом кортеже
num_elements = len(current_difference)
print(f"Количество элементов в итоговом кортеже: {num_elements}")  # Вывод количества элементов

Количество элементов в итоговом кортеже: 257


In [ ]:
# Дополнение к коду для обработки результата
# Присвоение обработанного результата переменной SFih
SFih = process_fuzzy_result(current_difference)

# Вывод значения SFih
print(f"Значение SFih: {SFih}")

Значение SFih: (18.0, 0.92, 0.94, 0.95, 0.96, 0.97, 0.98)


In [ ]:
# Вычисление EF = 1.4 - (0.03 * SFih)
# Функция для умножения дискретного колеблющегося нечеткого числа на константу
def multiply_fuzzy_number_with_constant(X, A):
    x, *parameters = X
    Z = round(A * x, 3)
    new_parameters = [round(1 - (1 - param) ** A, 2) for param in parameters]
    return (round(Z, 3), *new_parameters)

def difference_fuzzy_number_with_constant(X, A):
    # Распаковка параметров нечеткого числа
    x, *membership_degrees = X  # Извлекаем значение и степени принадлежности

    # Вычисление нового значения Z
    Z = A - x  # Сумма значения X и константы A

    # Параметры (степени принадлежности) остаются без изменений
    return (round(Z, 3), *membership_degrees)

# Умножаем SFih на 0.03
multiplied_result = multiply_fuzzy_number_with_constant(SFih, 0.03)

# Теперь теперь вычитаем результат от константы 1.4
EF = difference_fuzzy_number_with_constant(multiplied_result, 1.4)

# Вывод результата EF
print(f"Значение EF: {EF}")

Значение EF: (0.86, 0.07, 0.08, 0.09, 0.09, 0.1, 0.11)


Так как при умножении нечеткого колеблющегося числа на константу значения константы становятся показателями степеней, в которую возводятся значения *HFE*, то при возведении значений функции принадлежности в степень (-0.03) получаются значения, очень близкие к 1. Поскольку по формуле далее они вычитаются из 1, то итоговые значения степеней принадлежности *EF* очень близки к нулю, что в дальнейшем приводит к очень низким показателям степеней принадлежности итогового расчетного результата по модели.

In [ ]:
# Дополнение к коду для обработки результата
# Присвоение обработанного результата переменной EF_final
EF_final = process_fuzzy_result(EF)

# Вывод значения EF_final
print(f"Значение EF_final: {EF_final}")

Значение EF_final: (0.86, 0.07, 0.08, 0.09, 0.1, 0.11)


In [ ]:
# Вычисление UCP = UUCP_processsed_result * TCF * EF_final
def multiply_discrete_fuzzy_numbers(X, Y):
    # Распаковка параметров дискретных колеблющихся нечетких чисел
    x_value, *x_parameters = X  # Извлекаем значение и параметры X
    y_value, *y_parameters = Y  # Извлекаем значение и параметры Y

    # Список для хранения результатов
    result_parameters = []

    # Перебор всех параметров X и Y
    for x_param in x_parameters:
        for y_param in y_parameters:
            # Вычисление параметров для Z
            z_param = round(x_param * y_param, 2)
            result_parameters.append(z_param)

    # Вычисление значения Z
    Z_value = round(x_value * y_value, 2)

    return Z_value, result_parameters

# Сначала умножаем UUCP_processed_result на TCF
result_1_value, result_1_parameters = multiply_discrete_fuzzy_numbers(UUCP_processed_result, TCF)

# Теперь результат умножаем на EF_final
final_result_value, final_result_parameters = multiply_discrete_fuzzy_numbers((result_1_value, *result_1_parameters), EF_final)

# Упаковка итогового результата в кортеж
final_result = (final_result_value, *final_result_parameters)

# Вывод результата
final_parameters_str = ', '.join(map(str, final_result_parameters))
print(f"Результат произведения нечетких чисел UCP = {final_result} (где X = {final_result_value}, параметры = {{ {final_parameters_str} }})")

Результат произведения нечетких чисел UCP = (72.0, 0.0, 0.0, 0.0, 0.01, 0.01, 0.07, 0.08, 0.09, 0.1, 0.11, 0.0, 0.0, 0.0, 0.01, 0.01, 0.07, 0.08, 0.09, 0.1, 0.11) (где X = 72.0, параметры = { 0.0, 0.0, 0.0, 0.01, 0.01, 0.07, 0.08, 0.09, 0.1, 0.11, 0.0, 0.0, 0.0, 0.01, 0.01, 0.07, 0.08, 0.09, 0.1, 0.11 })


In [ ]:
# Дополнение к коду для обработки результата
# Присвоение обработанного результата переменной UCP
UCP = process_fuzzy_result(final_result)

# Вывод значения UCP
print(f"Значение UCP: {UCP}")

Значение UCP: (72.0, 0.0, 0.01, 0.07, 0.08, 0.09, 0.1, 0.11)


Вывод: колеблющиеся нечеткие множества не совсем подходят для использования в данной модели, так как большое количество нечетких слагаемых (со степенями принадлежности выше 0.5) при суммировании приводит к значениям степеней принадлежности результирующего *HFE* , близким к 1, а константы (если они близки к 0), при умножении на них *HFE* очень сильно cнижают итоговые значения степеней принадлежности результата. В итоге степень принадлежности расчетного параметра либо очень большая (около, либо равна 1), либо очень маленькая (около, либо равна 0) и ее значение наглядно не отражает уровни степеней принадлежности входных данных.

# **Вывод по проделанной работе**

Для рассмотренных моделей (*FPA*, *COCOMO II*, *UCP*) наибольшее количество информации об оценках стейкхолдеров позволяют сохранить нечеткие трапециевидные числа (треугольные нечеткие числа - их частный случай), с помощью которых можно отразить степень уверенности в оценках экспертов или параметрах модели, которые присваиваются по результатам этих оценок. При использовании интервальных нечетких трапециевидных чисел 2-го типа рассматривается только "положительная" информация о величине оцениваемого параметра (что оценка именно такого размера), а верхняя и нижняя функции принадлежности позволяют моделировать степень неопределенности в выборе самой функции принадлежности.

Интервальные интуиционистские нечеткие множества 2-го типа по алгоритму использования идентичны интервальным нечетким множествам 2-го типа, но они описывают степень принадлежности и непринадлежности элемента данному множеству, т.е. моделируют независимое рассмотрение как "положительной", так и "отрицательной" информации об оценке. Разность между единицей и суммой функций принадлежности и непринадлежности - это степень сомнения, что данные оценки (функций принадлежности и непринадлежности) именно такие.

Нечеткие множества, основанные на сомнениях, лучше подойдут для моделей оценки затрат на разработку ПО с меньшим количеством параметров, где предметом обсуждения является не размер отдельно взятого показателя (особенно когда их в модели достаточно много), а оценка проекта в целом, например, методом экспертных оценок «сверху вниз», «по аналогу», методом параметрических оценок, по модели *SLIM* или методом *PERT*, т.к. в данном типе нечетких множеств нечеткой является степень принадлежности определенного числа данному множеству (т.е. колебания относительно того, какая степень принадлежности будет у данного нечеткого числа). Также данный тип множеств может быть рассмотрен в дальнейших исследованиях как математический аппарат методов коллективного принятия решений (нечеткий метод Дельфи, методы ранжировки, покер-планирование и др.).
Кроме того, как показала практика, данный тип нечетких множеств очень чувствителен к размеру констант, когда на них происходит умножение НЧ, или они используются в качестве показателя степени, а также многократному суммированию или произведению нечетких параметров (более 3 слагаемых или множителей): при степенях принадлежности слагаемых выше 0.5 степени принадлежности результата стремятся к 0 или 1 и информативность модели снижается, так как результирующий аргумент нечеткого колеблющегося числа повторяет результат четкой модели, а величина колеблющегося нечеткого элемента, близкая к нулю, будет означать, что сомнения по поводу его принадлежности к данному множеству очень велики. В обратной ситуации, при стремления итоговой степени принадлежности к 1, получаем константу (т.е. четкое число) без дополнительной информации.